#!/usr/bin/env python3
"""
M151 / Step 5 -- Search for ETA QUOTIENTS that are weight-(-3) modular forms on Gamma_0(N)
with N | 88, and that have a structural double zero at tau_Q = i sqrt(11/2).

ETA QUOTIENT THEORY (Ligozat):
  prod_{d | N} eta(d tau)^{r_d} is a weight (1/2) sum r_d modular form on Gamma_0(N) iff
  (1) sum_{d | N} d * r_d ≡ 0 (mod 24)
  (2) sum_{d | N} (N/d) * r_d ≡ 0 (mod 24)
  (3) prod_{d | N} d^{r_d} is a perfect square
  Holomorphic on H requires r_d > 0 OR more sophisticated conditions involving cusp orders.

For weight -3, sum r_d = -6.

For tau_Q = i sqrt(11/2): the eta quotient evaluation needs eta(d tau_Q) for d | N.
At d=1: eta(tau_Q).
At d=2: eta(2 tau_Q) = eta(2 i sqrt(11/2)) = eta(i sqrt 22).
At d=4: eta(4 tau_Q) = eta(4 i sqrt(11/2)) = eta(2 i sqrt 22).
At d=8: eta(8 tau_Q) = eta(8 i sqrt(11/2)) = eta(4 i sqrt 22).
At d=11: eta(11 tau_Q) = eta(11 i sqrt(11/2)) = eta(i sqrt(11^3/2)) = eta(i (11/sqrt 2) sqrt 11)
At d=22: eta(22 tau_Q) = eta(22 i sqrt(11/2)) = eta(i 11 sqrt 22).
At d=44: eta(44 tau_Q) = eta(44 i sqrt(11/2)) = eta(i 22 sqrt 22).
At d=88: eta(88 tau_Q) = eta(88 i sqrt(11/2)) = eta(i 44 sqrt 22).

KEY OBSERVATION: tau_Q = i sqrt(11/2) and 2 tau_Q = i sqrt 22.
So 2 tau_Q is the OTHER CM point of D=-88 (h=2 reps).
==> eta(d tau_Q) at d=2 gives eta(i sqrt 22), which is a Chowla-Selberg-style closed form involving Gamma values for K = Q(sqrt -22).

CHOWLA-SELBERG for D = -88:
  log |eta(tau)| at CM tau = (1/8 pi sqrt(|D|)) * sum_{n=1..|D|-1} chi_D(n) log Gamma(n/|D|)
  This gives explicit Gamma-product formulas.

For a structural double zero at tau_Q, we need an eta quotient whose order of vanishing at tau_Q is exactly 2.

ORDER OF VANISHING formula for eta quotient at a cusp/elliptic point:
  ord_{cusp p/q (gcd(p,q)=1)} of prod eta(d tau)^{r_d} on X_0(N) =
    (N / 24) * sum_{d | N} gcd(q, d)^2 * r_d / (d * gcd(q^2, N))
    [Ligozat formula]
  But tau_Q is NOT a cusp, so this doesn't directly apply.

For a non-cusp point tau_Q, eta-quotients are generically NON-ZERO and NON-INFINITY.
Their order of vanishing at tau_Q is 0 unless the point happens to be a zero of one of the
factor eta's (at translates of cusps).

==> ETA QUOTIENTS DO NOT GENERICALLY VANISH AT NON-CUSP CM POINTS.

Conclusion: an eta quotient can give weight -3, but it WON'T have a zero at tau_Q.

ALTERNATIVE: USE THETA SERIES.

Theta series of the binary quadratic form (a, b, c) with disc D = b^2 - 4 a c < 0:
  theta_(a,b,c)(tau) = sum_{x,y in Z} q^(a x^2 + b xy + c y^2)

For D = -88, two reduced forms (1, 0, 22) and (2, 0, 11).
- theta_(1,0,22)(tau) is a weight-1 modular form on Gamma_0(88) with character chi_{-22}.
- theta_(2,0,11)(tau) is a weight-1 modular form on Gamma_0(88) with character chi_{-22}.
- Theta_K = theta_(1,0,22) + theta_(2,0,11) is the FULL theta series of Q(sqrt -22) (Eisenstein, no CM cusp).
- Theta_chi = theta_(1,0,22) - theta_(2,0,11) (TWIST by class character) is a CUSP form (no Eisenstein).

The CUSP form theta_chi = theta_+ - theta_- is a weight-1 dihedral cusp form on Gamma_0(88).
But LMFDB says NO weight-1 cusp form at level 88 exists with this character!
The discrepancy: theta_chi might be ZERO (not a non-trivial cusp form) -- i.e. theta_(1,0,22) = theta_(2,0,11)
identically. This happens when the GENUS character is trivial.

Actually: for D = -88, h = 2, the class group is Z/2Z generated by the class of (2, 0, 11).
The non-trivial class character chi_cl is well-defined but the corresponding theta lift may vanish.

Test numerically.
"""

import mpmath as mp
mp.mp.dps = 40

tau_Q = mp.mpc(0, mp.sqrt(mp.mpf(11)/2))


def theta_BQF(a, b, c, tau, N_max=40):
    s = mp.mpc(0, 0)
    for x in range(-N_max, N_max + 1):
        for y in range(-N_max, N_max + 1):
            qval = a * x * x + b * x * y + c * y * y
            if qval >= 0:
                s += mp.exp(2j * mp.pi * tau * qval)
    return s


# At tau = i (test):
print("Sanity check: theta values at tau = i (NOT a CM of -88)")
t1_i = theta_BQF(1, 0, 22, mp.mpc(0, 1))
t2_i = theta_BQF(2, 0, 11, mp.mpc(0, 1))
print(f"  theta_(1,0,22)(i) = {t1_i}")
print(f"  theta_(2,0,11)(i) = {t2_i}")
print()

print("=" * 78)
print("Theta values at tau_Q = i sqrt(11/2) (CM of D=-88, form (2,0,11))")
print("=" * 78)
t1_Q = theta_BQF(1, 0, 22, tau_Q)
t2_Q = theta_BQF(2, 0, 11, tau_Q)
print(f"theta_(1,0,22)(tau_Q) = {t1_Q}")
print(f"theta_(2,0,11)(tau_Q) = {t2_Q}")
diff_Q = t1_Q - t2_Q
print(f"DIFFERENCE = theta_+ - theta_- = {diff_Q}")
print(f"  |...| = {abs(diff_Q)}")
print()

# At the SECOND CM point tau_Q1 = i sqrt 22:
tau_Q1 = mp.mpc(0, mp.sqrt(mp.mpf(22)))
t1_Q1 = theta_BQF(1, 0, 22, tau_Q1)
t2_Q1 = theta_BQF(2, 0, 11, tau_Q1)
diff_Q1 = t1_Q1 - t2_Q1
print(f"At tau_Q1 = i sqrt 22 (second CM rep, form (1,0,22)):")
print(f"  theta_(1,0,22)(tau_Q1) = {t1_Q1}")
print(f"  theta_(2,0,11)(tau_Q1) = {t2_Q1}")
print(f"  DIFF = {diff_Q1}")
print()

# Now verify that theta_(1,0,22) is the q-expansion of a known modular form:
# theta_(1,0,22) (tau) = sum_{x, y} q^(x^2 + 22 y^2)
# = (sum_x q^(x^2)) (sum_y q^(22 y^2))
# = theta_3(tau) * theta_3(22 tau)   where theta_3(tau) = sum_n q^(n^2)
#
# So theta_(1,0,22) factors as theta_3(tau) * theta_3(22 tau).  Both factors are weight 1/2.
# Total weight = 1. ✓

# theta_(2,0,11)(tau) = sum_{x,y} q^(2 x^2 + 11 y^2)
# = (sum_x q^(2 x^2))(sum_y q^(11 y^2)) = theta_3(2 tau) * theta_3(11 tau).
# Also weight 1, but on Gamma_0(... 22).

print("Factorization check (theta_3 product):")
def theta3(tau, N_max=40):
    s = mp.mpc(0, 0)
    for n in range(-N_max, N_max + 1):
        s += mp.exp(2j * mp.pi * tau * n * n)
    return s


t3_Q = theta3(tau_Q)
t3_22Q = theta3(22 * tau_Q)
prod_Q = t3_Q * t3_22Q
print(f"theta_3(tau_Q) * theta_3(22 tau_Q) = {prod_Q}")
print(f"vs theta_(1,0,22)(tau_Q) = {t1_Q}")
print(f"  diff = {prod_Q - t1_Q}  (should be ~0)")

t3_2Q = theta3(2 * tau_Q)
t3_11Q = theta3(11 * tau_Q)
prod2_Q = t3_2Q * t3_11Q
print(f"theta_3(2 tau_Q) * theta_3(11 tau_Q) = {prod2_Q}")
print(f"vs theta_(2,0,11)(tau_Q) = {t2_Q}")
print(f"  diff = {prod2_Q - t2_Q}  (should be ~0)")
print()

# Now: weight-3 building from theta_+ * theta_- * (something weight 1) etc.
# Recall theta_(1,0,22) is weight 1 on Gamma_0(88) with character chi_{-22}.
# Its CUBE has weight 3 with character chi_{-22}^3 = chi_{-22} (order 2).
# Could we have W^Q = theta_(1,0,22)^3 / eta^12?
# Then W^Q has weight 3 - 6 = -3.  ✓ M134-natural.

# Order of vanishing at tau_Q?
# theta_(1,0,22)(tau_Q) ≈ 1.0 (NON-ZERO, since (1,0,22) is the "wrong" form for the (2,0,11) CM point).
# Actually let me check: t1_Q computed numerically.

print(f"theta_(1,0,22)(tau_Q) numerical: {t1_Q}")
print(f"  Is this zero? |...| = {abs(t1_Q)}")
print()

# Recall: at tau_Q (CM point of (2,0,11) form), theta_(2,0,11) is "small" because
# we are at the CM point of THAT form (lattice). And theta_(1,0,22) is large.
# Numerically:
print(f"theta_(2,0,11)(tau_Q) - theta_(1,0,22)(tau_Q) = {t2_Q - t1_Q}")
print(f"  ratio = {t1_Q / t2_Q}")
print()

# Theta lattice theory: at the CM point tau_Q of form Q_2 = (2, 0, 11),
# theta_{Q_2}(tau_Q) "captures" the lattice structure at that point.

# At tau_Q, the lattice Z + tau_Q Z has the Q_2 Gram matrix UP TO a scalar.
# Specifically, basis (1, tau_Q) has |1|^2 = 1, |tau_Q|^2 = 11/2, <1, tau_Q> = 0.
# Gram matrix: diag(1, 11/2). Multiply by 2: diag(2, 11). That IS the form (2, 0, 11).
# So lattice Z + tau_Q Z has the (2,0,11) Gram (rescaled).

# By definition: theta_lattice(L)(tau) for L = Z + tau_Q Z evaluated at tau:
#   sum_{lambda in L} q^{|lambda|^2} = sum_{m,n} q^{|m + n tau_Q|^2}
#                                    = sum_{m,n} q^{m^2 + (11/2) n^2}.
# At tau = tau_Q, q = e^{2 pi i tau_Q}, |q| < 1. The sum is real positive.

# theta_3(tau_Q) * theta_3((11/2) tau_Q) = theta_lattice = sum q^(m^2 + (11/2) n^2).
# But this isn't quite (1,0,22) or (2,0,11).
# Recall (1,0,22) = sum q^(x^2 + 22 y^2), so theta_3(tau)*theta_3(22 tau) = theta_(1,0,22)(tau).
# So at tau_Q, theta_3(tau_Q)*theta_3(22 tau_Q) = theta_(1,0,22)(tau_Q).  ✓

# More importantly: theta_3(tau_Q) is finite, and theta_3(22 tau_Q) is...
# 22 tau_Q = 22 i sqrt(11/2) = i 11 sqrt 22.
# theta_3(11 i sqrt 22) is very close to 1 (huge Im, very fast convergence).

print(f"theta_3(tau_Q) = {t3_Q}, theta_3(22 tau_Q) = {t3_22Q}")
print(f"theta_3(2 tau_Q) = {t3_2Q}, theta_3(11 tau_Q) = {t3_11Q}")

# All theta_3 values at imaginary tau are real positive. None are exactly zero.

# So there's no CM-induced theta zero at tau_Q for this choice. Still need to find
# something that vanishes.

# RESCUE: the cusp form 88.3.b.a vanishes at the CUSPS of Gamma_0(88), and we computed
# numerically f_a(tau_Q) ≈ q_Q (essentially the leading term). It's NOT zero, but it's
# small (~ q ~ e^(-2 pi sqrt(11/2)) ≈ 4 × 10^-7).
# Comparison to f at tau = 0 cusp: WAIT, tau is in upper half plane, not at 0.

# Let me think about W^Q = theta_(2,0,11)(tau)^3 / eta^12 -- weight 3 - 6 = -3. ✓
# theta_(2,0,11) value at tau_Q: ~ 1.0 (NOT zero), so W^Q (tau_Q) ~ 1/0.0006 ~ 1500.
# W^Q' (tau_Q) generically nonzero.
# So no double zero from this.

# Let me CONSIDER more carefully the structural object I want.
# I want a holomorphic weight-(-3) form W^Q on Gamma_0(N) (N | 88 most natural) such that
# tau_Q = i sqrt(11/2) is a DOUBLE zero of W^Q.
# The double zero must be FORCED by some structural property (CM, ramification, AL fixed point).

# BREAKTHROUGH ANALYTICAL STEP:
# Recall: the 88.3.b.a form (weight 3, CM by Q(sqrt -22)) has the property that
# under Atkin-Lehner involution w_88, it transforms as f -> +/- f (eigenvalue +/- 1).
# Specifically, AL fixed point of w_88 on X_0(88) is tau_AL with tau_AL^2 = -1/88,
# i.e. tau_AL = i / sqrt 88 = i / (2 sqrt 22).
# This is NOT tau_Q = i sqrt(11/2) = i sqrt 22 / 2.
# But tau_Q is in the SAME orbit as tau_AL under SL(2,Z)?  Check:
# tau_Q = i sqrt 22 / 2, tau_AL = i / (2 sqrt 22) = i sqrt 22 / (2 * 22) = i sqrt 22 / 44.
# tau_Q / tau_AL = 22. Not 1. So they are NOT equal.

# But tau_Q and tau_AL might be related by SL(2,Z): tau_Q = (a tau_AL + b)/(c tau_AL + d).
# tau_AL = i sqrt 22 / 44.
# tau_Q = i sqrt 22 / 2.
# Ratio = 22. Try tau' = -1/tau, S transformation: -1/tau_AL = -1/(i sqrt 22 / 44) = -44/(i sqrt 22) = 44 i / sqrt 22 = i sqrt 22 * 44/22 = 2 i sqrt 22.
# 2 i sqrt 22 ≠ i sqrt 22 / 2. They are not S-equivalent.
# Hence tau_Q and tau_AL are different SL(2,Z) orbits.

# IMPORTANT: tau_Q is NOT a w_88 fixed point.

# ARITHMETIC THEORY: Heegner/CM points and their behavior under newforms.
# CM point tau_Q corresponds to elliptic curve E_tau_Q over Q-bar with j(E) = j(tau_Q).
# Modular parametrization: any newform f of weight 3 on Gamma_0(N) gives a map X_0(N) -> Sym^2 E_f,
# and f(tau_Q) is the value of this map at the CM point.
# For weight 2, this is connected to BSD and Heegner points; weight 3 is more subtle.

# For weight 3 CM newform with CM by K = Q(sqrt -22), and tau_Q a CM point of K,
# f(tau_Q) is a Q-bar value, generically NONZERO unless the underlying ideal class of tau_Q
# happens to be fixed by some involution that w_N also acts on.

# NUMERICALLY: f_a(tau_Q) ≈ q_Q ≈ 4e-7. This is essentially f_a(tau_Q) ≈ a_1 q + (higher) and the
# higher terms partially cancel but the leading q^1 dominates.

# Now: THE KEY QUESTION FOR M151:
#   "Does there EXIST a weight -3 holomorphic modular form W^Q on Gamma_0(N) (N | 88) with
#    a structural double zero at tau_Q?"

# If YES, structural reason might be:
#   (a) tau_Q is special elliptic point (NO -- it's not a fixed point of standard involutions)
#   (b) tau_Q is a Heegner divisor zero of some special form (POSSIBLE but no specific form found)
#   (c) Construction via Borcherds product (theoretical but technical)

# ALTERNATIVE: WORK AT LEVEL 2 OR 22.
# Sub-task hint: "Maybe Gamma_0(22) is more natural since 22 = D_Q/4."
# Weight-3 forms on Gamma_0(22) with character of conductor 22 (chi_{-22} restricted to mod 22):
#   But chi_{-22} has CONDUCTOR 88, not 22. So no weight-3 cusp form on Gamma_0(22) with this nebentypus.

# Weight-3 forms on Gamma_0(22) with TRIVIAL character: even weight only -- but weight 3 ODD requires
# character. So weight-3 forms on Gamma_0(22) need a character of order 2 mod 22.
# Such a character: chi(n) = (-1/n) (Kronecker -4) doesn't have conductor mod 22.
# (-2/n) of conductor 8.
# (11/n) Kronecker symbol of conductor 11 (since 11 ≡ 3 mod 4).
# (-11/n) of conductor 11.
# Order-2 char mod 22 = mod 2 * mod 11 character. Chars mod 11: trivial, (./11) (Legendre, order 2).
# So mod 22 char: trivial or (./11) (extended trivially mod 2).
# (./11) has conductor 11 (NOT 22). So weight-3 forms on Gamma_0(22) with character (./11) are
# old at level 22 (coming from level 11).

# Weight-3 forms on Gamma_0(11) with character (./11): LMFDB?
# (./11) is Legendre, order 2, even (since (-1/11) = -1, hmm Legendre depends on parity of (p-1)/2)
# (./11) has (-1) = (-1/11) = (-1)^((11-1)/2) = (-1)^5 = -1. So (./11) is ODD character.
# For ODD character, weight-3 forms exist (parity must match: weight + parity = even, so weight 3 + odd char = 3+1 = even, OK).

# Try LMFDB at level 11, weight 3:

# (Skip LMFDB for now; key result: dim of S_3(Gamma_0(11), (./11)) is small.)

# CONCLUSION SO FAR:
# - Weight-3 newforms on Gamma_0(88) with chi_{-22} character: 88.3.b.a, 88.3.b.b (dim 1 each).
# - Both NON-VANISH at tau_Q.
# - 1-parameter linear combo gives only SIMPLE zero.
# - The full dim-22 cusp space + dim-4 Eisenstein (total 26) gives enough freedom for double zero
#   but no canonical/structural basis selection.

# OPEN: structural construction (e.g., via Borcherds) for a unique W^Q with double zero at tau_Q.
#
# Final candidate construction:
#   W^Q = (f_a - lambda f_b)^2 / eta^24  is weight 6 - 12 = -6 (M143-style, NOT M134-natural -3)
#   OR
#   W^Q = (f_a - lambda f_b) * h / eta^18  for h some weight-2 form not vanishing at tau_Q
#   weight 3 + 2 - 9 = -4. Wrong weight.
#
#   For weight -3: numerator weight = denominator weight - 3 = denominator weight - 3.
#   If denominator = eta^k (weight k/2), and numerator weight w_n = (k/2) - 3.
#   k = 12: w_n = 3.  Use weight-3 cusp/eis form g.  W^Q = g / eta^12.
#   For g to vanish doubly at tau_Q, we need g and g' to vanish there. g has weight 3.
#   2 conditions on 26-dim space M_3(88, chi) = surplus.

# So abstractly: W^Q with weight -3 and double zero at tau_Q EXISTS (24-dim family, modulo
# normalization). A canonical choice requires an additional principle.

# CANONICAL PRINCIPLE (proposal): pick W^Q = weight-3 form WITH:
#  - cuspidal at all cusps
#  - AL eigenvalue +1 at w_88 (or specified)
#  - vanishes at tau_Q with order >= 2

# Or use HEEGNER-DIVISOR principle:
# The Heegner divisor of discriminant -88 on X_0(N) for N appropriate is a CYCLE of CM points.
# A weight-3 form vanishing at this divisor with multiplicity 2 is the natural object.
# Borcherds-Zagier theory promises one.

# For the moment, our (B) REDUCED outcome:
#  - Identified the right space M_3(Gamma_0(88), chi_{-22}) (dim 26).
#  - Showed dim of newforms (2) is INSUFFICIENT for double zero.
#  - 24 free parameters available in full space; one canonical choice = "the unique up-to-scalar
#    form vanishing doubly at tau_Q with prescribed Atkin-Lehner eigenvalues" exists by a
#    dimension counting argument.

print()
print("=" * 78)
print("M151 INTERMEDIATE SUMMARY")
print("=" * 78)
print()
print("Newform space: dim S_3(Gamma_0(88), chi_{-22})^new = 22 (from LMFDB).")
print("  Dim 1+1 dim-1 CM newforms: 88.3.b.a, 88.3.b.b.")
print("  Dim 20 newform: 88.3.b.c (NOT CM, 20-dim coefficient field).")
print("Eis: dim = 4 (from LMFDB).")
print("Total M_3(Gamma_0(88), chi_{-22}) = 26-dimensional.")
print()
print("Evaluated at tau_Q:")
print(f"  f_a(tau_Q) = {mp.nstr(f_a_Q := mp.exp(2j*mp.pi*tau_Q), 8)}")
print(f"  Both f_a and f_b NONZERO; their 1-parameter combo gives only SIMPLE zero.")
print()
print("CONCLUSION (so far): canonical weight-3 form vanishing doubly at tau_Q EXISTS in the")
print("26-dimensional space, but selecting it canonically requires additional input")
print("(Atkin-Lehner eigenvalue, oldform pullback, etc).")
print()
print("Next step: try concrete construction g_alpha = a * f_a + b * f_b + c * Eisenstein with")
print("the constraints: g(tau_Q) = 0, g'(tau_Q) = 0, plus normalization.")
