#!/usr/bin/env python3
"""
M134 -- N=1 SUGRA F-term construction with W(tau) such that V_F has min at tau=i.

Setup:
  Kahler potential: K = -3 log(-i (tau - bar tau)) = -3 log(2 Im tau)
  Superpotential:   W(tau) -- holomorphic, modular weight -3 (under SL(2,Z))
                    so that the physical F-term V_F is SL(2,Z)-invariant.

  V_F = e^K (G^{ij*} D_i W (D_j W)* - 3 |W|^2)
      = (1/(2 Im tau)^3) [ (2 Im tau)^2/3  |D_tau W|^2 - 3 |W|^2 ]
      = (1/(2 Im tau)^3) [ (2 Im tau)^2/3  |D_tau W|^2 - 3 |W|^2 ]
  with D_tau W = d_tau W + (d_tau K) W = d_tau W + (3i)/(2 Im tau)/(-1) * (-1) W
              = d_tau W + (3 i/(tau-bar tau)) * (-1) W

  Wait, careful: K = -3 log(-i(tau - bar tau))
  d_tau K = -3 * d_tau[ -i(tau-bar tau) ] / (-i(tau-bar tau))
          = -3 * (-i) / (-i(tau-bar tau))
          = -3 / (tau - bar tau)
          = 3i / (2 Im tau)            [since tau-bar tau = 2i Im tau]

  Hmm that's not right.  tau - bar tau = 2 i Im tau, so 1/(tau-bar tau) = 1/(2 i Im tau) = -i/(2 Im tau).
  d_tau K = -3 * (-i)/(-i (tau-bar tau)) = -3 / (tau-bar tau) = -3 * (-i)/(2 Im tau) = 3i/(2 Im tau).
  Hmm: -3/(tau-bar tau) = -3/(2i Im tau) = -3/(2i) / Im tau = (-3 * (-i)/2) / Im tau = (3i/2)/Im tau.
  So d_tau K = 3i/(2 Im tau).  Good.

  D_tau W = d_tau W + (d_tau K) W = W'(tau) + 3i/(2 Im tau) W(tau)

  At tau = i, Im tau = 1, so d_tau K = 3i/2, and:
    D_tau W (i) = W'(i) + (3i/2) W(i)

  G_{tau bar tau} = d_tau d_bar K = d_bar [3i/(2 Im tau)]
                  = 3i/2 * d_bar [1/Im tau]
                  Im tau = (tau-bar tau)/(2i)
                  d_bar (Im tau) = -1/(2i) = i/2 (... d_bar tau = 0, d_bar bar tau = 1)
                  Wait: Im tau = (tau - bar tau)/(2i), so d_bar (Im tau) = -1/(2i) = i/2.
                  Hmm signs...  Actually Im tau = (tau-tau_bar)/(2i), and
                  d_bar(Im tau) = d/d(tau_bar) ((tau-tau_bar)/(2i)) = -1/(2i) = i/2.
                  d_bar (1/Im tau) = -1/(Im tau)^2 * (i/2) = -i/(2 (Im tau)^2)
                  G_{tau bar tau} = 3i/2 * (-i/(2 (Im tau)^2)) = 3/(4 (Im tau)^2)

  Hmm, the standard SUGRA T-modulus has G_TT* = 3/(T+T*)^2 ≡ 3/(2 Im tau)^2
  so G_TT* = 3/(2 Im tau)^2. Above I got 3/(4 (Im tau)^2) = 3/(2 Im tau)^2 with a 1/4 vs 1/4? Let me redo:
  3/(2 Im tau)^2 = 3/(4 (Im tau)^2). OK same thing.
  G_TT* = 3/(2 Im tau)^2.  Inverse: G^{TT*} = (2 Im tau)^2 / 3.   Confirmed.

  V_F = e^K [G^{ij*} D_i W (D_j W)* - 3 |W|^2]
  With single chiral tau:
      e^K = e^{-3 log (2 Im tau)} = (2 Im tau)^{-3}
      G^{tau bar tau} = (2 Im tau)^2 / 3
      |D_tau W|^2 = |W'(tau) + (3i/(2 Im tau)) W(tau)|^2

      V_F = (2 Im tau)^{-3} [ (2 Im tau)^2 / 3 * |D_tau W|^2  - 3 |W|^2 ]

  At a tau-min, we need:
    V_F(tau_min) = 0 (Minkowski) requires |D_tau W|^2 = (3 |W|^2 / G^{tau bar tau}) = 9 |W|^2 / (2 Im tau)^2.
    So D_tau W = (3 e^{i alpha}/(2 Im tau)) W. With phase free.
    For SUSY-Minkowski, need W = 0, D_tau W = 0 simultaneously. That's an over-constrained
    system on a single complex variable. Generally only with extra fields.

  Modular invariance: under tau -> g tau = (a tau + b)/(c tau + d), c tau + d ≠ 0,
    K -> K + log|c tau + d|^2 = K + log(c tau + d) + log(c bar tau + d)
    So Kahler transformation with log f, f = (c tau + d).
    For V_F invariance, W -> (c tau + d)^{-3} W (modular weight -3).

  GOAL: construct holomorphic modular form W(tau) of weight -3 with
        W(i) = 0  and  W'(i) ≠ 0 (so that D_tau W (i) ∝ W'(i) ≠ 0 and V_F(i) > 0)
        OR
        W(i) ≠ 0 and D_tau W (i) ≠ 0 such that the F-term gradient flow has min at tau=i.

  But weight-(-3) modular forms... the ring of modular forms is generated by E_4 (wt 4), E_6 (wt 6).
  Weight -3 doesn't fit in classical holomorphic modular forms. We need either:
     - eta-like forms with rational weight. eta has weight 1/2; eta^{-6} has weight -3 and is holomorphic
       on H but blows up at cusp i*infty. Use eta^{-6} as a starting point.
     - Or quasi-modular E_2 (weight 2)... product like E_4^{-3/4} not single-valued.

  CANONICAL ANSATZ: W(tau) = c1 / eta(tau)^6 + c2 E_4(tau) E_6(tau) / eta(tau)^{18}  + ...
    All factors with weight chosen to give net weight -3.
    eta has weight 1/2, so 1/eta^6 has weight -3.   E_4 E_6 / eta^{18} has weight 4+6-18*(1/2) = 4+6-9 = 1.
    So that 2nd term has weight 1, not -3.  Need weight -3 -- E_4 E_6 / eta^{26}.

  Let me restart. Want holomorphic W of weight -3 (allow eta-poles at cusp).
  Building blocks at weight -3:
    1/eta^6                          weight -3
    E_4 / eta^{14}                  weight 4 - 7 = -3
    E_6 / eta^{18}                  weight 6 - 9 = -3
    E_4 E_6 / eta^{20}              weight 4+6 - 10 = 0; not -3
    E_4^2 / eta^{22}                weight 8 - 11 = -3
    Delta / eta^{30}                weight 12 - 15 = -3 (= 1/eta^6 since Delta = eta^{24})
    E_6^2 / eta^{30}                weight 12 - 15 = -3
    j_invariant / eta^something:    j has weight 0, doesn't shift

  Actually basis of WK holomorphic forms is generated multiplicatively. For weight -3
  we have: 1/eta^6 * (any weight-0 modular function = polynomial in j).

  W(tau) = (1/eta^6) * P(j(tau))    where P is polynomial in j.

  For W(i) = 0: P(j(i)) = P(1728) = 0. So P(j) = (j - 1728) Q(j).
  Simplest: W(tau) = (j(tau) - 1728) / eta(tau)^6.

  At tau = i:  W(i) = 0 (since j(i)=1728).
              W'(i) = j'(i) / eta(i)^6 + (j(i)-1728) * d_tau (1/eta^6) (i)
                    = j'(i) / eta(i)^6  [second term zero since j-1728 = 0]
              And j'(i) = -2 pi i E_6 E_4^2 / Delta (i) = 0 (E_6(i)=0).
              So W'(i) = 0 too. (j has a critical point at tau=i.)

  Damn. Need higher-order terms.

  W''(i) = (j-1728)''/eta^6 (i) = -2 pi^2 E_4(i)^4 / Delta(i) / eta(i)^6
                                = -3456 pi^2 E_4(i) / eta(i)^6
                                (using j'' = -3456 pi^2 E_4(i) at tau=i)

  So near tau=i: W(tau) = -1728 pi^2 E_4(i) (tau-i)^2 / eta(i)^6 + O((tau-i)^3).

  D_tau W (i) = W'(i) + (3i/2) W(i) = 0 + 0 = 0.
  So at tau = i: V_F(i) = (1)^{-3} [ ... |0|^2 - 3 |0|^2 ] = 0.
  V_F(i) = 0 vacuum (Minkowski). Good.

  Mass: V_F is quadratic in (tau - i)? Need to expand.
    V_F = (2 Im tau)^{-3} [ (2 Im tau)^2 / 3 |D_tau W|^2 - 3 |W|^2 ]

  Near tau=i, |W|^2 ~ |W''(i)/2|^2 |tau-i|^4 (quartic).
  D_tau W = W' + (3i/(2 Im tau)) W.
  W'(tau) = W''(i) (tau-i) + (1/2) W'''(i) (tau-i)^2 + ...
  W'(i) = 0 already; W'(near i) = W''(i) (tau-i) + ...
  W (near i) ~ (1/2) W''(i) (tau-i)^2.
  D_tau W ~ W''(i) (tau-i) + (3i/2) * (1/2) W''(i) (tau-i)^2  + (small Im tau corrections)
       ~ W''(i) (tau-i)  to leading order.

  |D_tau W|^2 ~ |W''(i)|^2 |tau-i|^2.

  V_F(tau) ~ (2)^{-3} [ (2)^2/3 |W''(i)|^2 |tau-i|^2 - 3 * |W''(i)/2|^2 |tau-i|^4 ]
           = (1/8) [ (4/3) |W''(i)|^2 |tau-i|^2 - (3/4) |W''(i)|^2 |tau-i|^4 ]
           = (1/6) |W''(i)|^2 |tau-i|^2 - (3/32) |W''(i)|^2 |tau-i|^4 + ...

  So V_F has a QUADRATIC minimum at tau=i! Good.

  Mass^2 (in canonical Kahler coords):
    canonical d phi = sqrt(2 G_TT*) d tau = sqrt(2 * 3/(2 Im tau)^2) d tau = sqrt(6)/(2 Im tau) d tau
    At tau=i: d phi = sqrt(6)/2 d tau = sqrt(3/2) d tau.
    So |d tau|^2 = (2/3) |d phi|^2.
    V_F ~ (1/6) |W''(i)|^2 |tau-i|^2 = (1/6) |W''(i)|^2 * (2/3) |phi|^2 = (1/9) |W''(i)|^2 |phi|^2
    m^2 = (2/9) |W''(i)|^2  (since V = (1/2) m^2 |phi|^2 in canonical coords, careful with cmplx)

  More carefully: V_F = (1/6) |W''(i)|^2 (x^2 + (y-1)^2)  where x=Re tau, y=Im tau.
  In canonical coords phi = phi_1 + i phi_2 with G_TT* d tau d bar tau = d phi d bar phi,
  so d phi = sqrt(G_TT*) d tau = sqrt(3)/(2 Im tau) d tau (real units phi_1, phi_2).
  At tau=i (Im tau = 1): d phi = (sqrt(3)/2) d tau.
  So x = (2/sqrt(3)) phi_1, (y-1) = (2/sqrt(3)) phi_2.
  V_F = (1/6) |W''(i)|^2 * (4/3) (phi_1^2 + phi_2^2) = (2/9) |W''(i)|^2 (phi_1^2 + phi_2^2).
  Standard: V = (1/2) m^2 (phi_1^2 + phi_2^2)
  ==> m^2 = (4/9) |W''(i)|^2.

  Numerical: W''(i) = -3456 pi^2 E_4(i) / eta(i)^6.
  eta(i)^6 = (eta(i))^6 = 0.7682254^6 = 0.20577...
  Let's mpmath check.
"""

import mpmath as mp
mp.mp.dps = 30

# Building blocks
G14 = mp.gamma(mp.mpf(1)/4)
E4i = 3 * G14**8 / (2*mp.pi)**6
eta_i = G14 / (2 * mp.pi**(mp.mpf(3)/4))
Delta_i = E4i**3 / 1728   # since j(i) = 1728 and Delta = E4^3/j (when E6=0)

print("="*70)
print("M134 -- SUGRA F-term construction with W(tau) = (j-1728)/eta^6")
print("="*70)
print(f"G(1/4) = {G14}")
print(f"E_4(i) = {E4i}")
print(f"eta(i) = {eta_i}")
print(f"eta(i)^6 = {eta_i**6}")
print(f"Delta(i) = {Delta_i}")
print()

# W''(i)
W_pp = -3456 * mp.pi**2 * E4i / eta_i**6
print(f"W''(i) = -3456 pi^2 E_4(i) / eta(i)^6 = {W_pp}")
print(f"|W''(i)|^2 = {abs(W_pp)**2}")
print()

# m^2 = (4/9) |W''(i)|^2 in units where Mpl=1
m2_F = mp.mpf(4)/9 * abs(W_pp)**2
print(f"m^2 (SUGRA) = (4/9) |W''(i)|^2 = {m2_F}")
print(f"m^2 in M_pl^2 (with W in M_pl^3): trans-Planckian.")
print()

# In closed form:
# |W''(i)|^2 = (3456 pi^2 E_4(i))^2 / |eta(i)|^{12}
#            = 3456^2 pi^4 E_4(i)^2 / eta(i)^{12}
# eta(i)^{12} = (G(1/4)/(2 pi^{3/4}))^12 = G(1/4)^{12}/(2^{12} pi^9)
# E_4(i)^2 = 9 G(1/4)^{16}/(2 pi)^{12} = 9 G(1/4)^{16}/(2^{12} pi^{12})
# So:
# |W''(i)|^2 = 3456^2 * pi^4 * 9 G(1/4)^{16}/(2^{12} pi^{12}) / [G(1/4)^{12}/(2^{12} pi^9)]
#            = 3456^2 * 9 * pi^4 * G(1/4)^{16}/(2^{12} pi^{12}) * (2^{12} pi^9)/G(1/4)^{12}
#            = 3456^2 * 9 * pi^4 * G(1/4)^4 * pi^{9-12}
#            = 3456^2 * 9 * pi * G(1/4)^4
# Wait: pi^{4 - 12 + 9} = pi^1.
# = 3456^2 * 9 * pi * G(1/4)^4

# m^2 = (4/9) * 3456^2 * 9 * pi * G(1/4)^4 = 4 * 3456^2 * pi * G(1/4)^4
m2_closed = 4 * 3456**2 * mp.pi * G14**4
print(f"m^2 closed form: 4 * 3456^2 * pi * G(1/4)^4 = {m2_closed}")
print(f"diff: {abs(m2_F - m2_closed)}")
print()

# Pretty form: 3456 = 2 * 1728 = 2^7 * 3^3.
# 4 * 3456^2 = 4 * 11943936 = 47775744 = 2^14 * 3^6
# So m^2 = 2^14 * 3^6 * pi * G(1/4)^4
print(f"m^2 = 2^14 * 3^6 * pi * G(1/4)^4 = {2**14 * 3**6 * mp.pi * G14**4}")
print()

print("="*70)
print("STABILITY -- check |D_tau W|^2 - 3|W|^2 minimum at tau=i is positive")
print("="*70)

# At tau = i, V_F(i) = 0 (Minkowski vacuum), and the leading behavior is
# V_F(tau) ~ (2/9) |W''(i)|^2 (phi_1^2 + phi_2^2) > 0 for phi != 0.
# So tau = i is a TRUE LOCAL MINIMUM of V_F with V_F(i) = 0.
# Mass is positive: m_tau^2 > 0.

# Compare to KKLT-style scale: in KKLT m_tau^2 ~ a^2 |A|^2 e^{-2 a Re T} / Re T
# where T = i sigma + theta. Our W ~ 1/eta^6 has e^{-pi tau/2} suppression at large Im tau
# (since eta(tau) ~ e^{i pi tau / 12}); but for finite Im tau ~ 1, suppression is mild.

# Now: a key consistency check -- under tau -> -1/tau (S transformation), tau=i is a fixed point.
# Under T transformation tau -> tau + 1, tau=i goes to tau = 1+i. Not a fixed point.
# So tau=i is fixed only by S, NOT by T.
# Real fundamental domain F = {|tau|>=1, |Re tau|<=1/2}; tau=i is on boundary.

# Modular invariance of V_F: Under T (tau -> tau+1), eta(tau+1) = e^(i pi/12) eta(tau),
# j(tau+1) = j(tau), so W = (j-1728)/eta^6 -> e^(-i pi/2) W = -i W.  Not equal to W!
# Phase change W -> e^(-i pi/2) W. Then |W|^2, |D_tau W|^2 unchanged.
# So |W|^2 invariant under T.
# Under S (tau -> -1/tau), eta(-1/tau) = sqrt(-i tau) eta(tau), j is invariant.
# So W -> (-i tau)^{-3} W up to phase = (i tau)^3 W ... phase multiplier (c tau + d)^{3} for weight -3.
# G_TT* transforms covariantly. V_F is invariant by construction.
# OK so V_F is genuinely modular-invariant. It does NOT distinguish tau=i from tau=ANY other
# point in the SL(2,Z) orbit of tau=i.

# But the orbit of tau=i under SL(2,Z) is exactly the union of zeros of E_6, which on the
# fundamental domain F contains ONLY tau=i (E_6 has only one zero in F, at tau=i).
# So there are no "other" minima in F.

# What about tau=rho? We need V_F(rho) > 0 (since rho is not a min).
# At tau=rho: W(rho) = (j(rho) - 1728)/eta(rho)^6 = (0 - 1728)/eta(rho)^6 = -1728/eta(rho)^6.
# |W(rho)|^2 = 1728^2 / |eta(rho)|^12.
# D_tau W (rho) = W'(rho) + (3i/2 Im rho) W(rho) -- nonzero in general.
# So V_F(rho) is a sum of positive terms minus 3 |W|^2; need to compute.

# Numerical:
from mpmath import sqrt
sqrt3 = mp.sqrt(3)
rho = mp.mpc(-mp.mpf(1)/2, sqrt3/2)
print(f"rho = {rho}")

# eta(rho) -- mpmath via product
def eta_via_product(tau, terms=200):
    qq = mp.exp(2 * mp.pi * 1j * tau)
    out = mp.mpf(1)
    for n in range(1, terms):
        out *= 1 - qq**n
    return qq**(mp.mpf(1)/24) * out

eta_rho = eta_via_product(rho)
print(f"eta(rho) = {eta_rho}")
print(f"|eta(rho)| = {abs(eta_rho)}")
# Closed form: |eta(rho)| = 3^(1/8) Gamma(1/3)^(3/2) / (2 pi)
# Verify: Chowla-Selberg gives |eta(rho)|^2 = sqrt(3)/(2 pi) Gamma(1/3)^3 ... need to double-check
G13 = mp.gamma(mp.mpf(1)/3)
eta_rho_pred = mp.exp(-mp.pi * 1j / 24) * 3**(mp.mpf(1)/8) * G13**(mp.mpf(3)/2) / (2*mp.pi)
# This is the absolute value; for the phase we have eta(rho) = e^(-i pi/24) * |...|
print(f"|eta(rho)| via Chowla-Selberg: {abs(eta_rho_pred)}")

# At tau=rho: j(rho)=0. So W(rho) = -1728/eta(rho)^6.
W_rho = -1728/eta_rho**6
print(f"W(rho) = {W_rho}")
print(f"|W(rho)|^2 = {abs(W_rho)**2}")
print()

# Now V_F at tau=rho
Im_rho = mp.im(rho)
print(f"Im(rho) = {Im_rho} = sqrt(3)/2 = {sqrt3/2}")
print()
print(f"V_F(rho) requires W'(rho) and D_tau W (rho).")
print(f"This is a sanity check that rho is NOT also a zero of V_F.")
print(f"(If both i and rho were zero-energy minima, the bridge degeneracy from A60")
print(f"would re-emerge.)")

# Compute V_F(rho) numerically
# W(tau) = (j(tau) - 1728) / eta(tau)^6 -> needs derivative.
# Use finite difference for D_tau W, and Hessian for V_F.

def W_full(tau):
    # j(tau) - 1728 = E_6^2 / Delta
    # We compute via E_4, E_6, eta directly (mpmath builtins)
    # But mpmath has jtheta only; let me code from q-series with reasonable cutoff
    q = mp.exp(2 * mp.pi * 1j * tau)
    # E_4
    e4 = mp.mpf(1)
    e6 = mp.mpf(1)
    n_terms = 100
    s4 = mp.mpf(0)
    s6 = mp.mpf(0)
    for n in range(1, n_terms):
        sigma3 = sum(d**3 for d in range(1, n+1) if n % d == 0)
        sigma5 = sum(d**5 for d in range(1, n+1) if n % d == 0)
        s4 += sigma3 * q**n
        s6 += sigma5 * q**n
    e4 = 1 + 240 * s4
    e6 = 1 - 504 * s6
    # eta
    et = mp.mpf(1)
    for n in range(1, n_terms):
        et *= 1 - q**n
    et *= q**(mp.mpf(1)/24)
    # j - 1728 = E_6^2 / Delta = E_6^2 * 1728 / (E_4^3 - E_6^2)
    j_m_1728 = 1728 * e6**2 / (e4**3 - e6**2)
    return j_m_1728 / et**6

# numerical W''(rho) etc — skip detailed; just check V_F is bounded away from 0.
W_rho_num = W_full(rho)
print(f"W(rho) numerical = {W_rho_num}")
print(f"|W(rho)|^2 numerical = {abs(W_rho_num)**2}")

# Use that |W(rho)|^2 ~ 1728^2 / |eta(rho)|^12
# eta(rho)^12 = ?
eta_rho_12 = eta_rho**12
print(f"eta(rho)^12 = {eta_rho_12}")
print(f"|eta(rho)^12| = {abs(eta_rho_12)}")
# So 1728^2 / |eta(rho)|^12 = ?
W_sq_rho = 1728**2 / abs(eta_rho)**12
print(f"|W(rho)|^2 = 1728^2/|eta|^{{12}} = {W_sq_rho}")

# Now compute V_F(rho).
# V_F = (2 Im tau)^{-3} * [ (2 Im tau)^2/3 |D_tau W|^2 - 3 |W|^2 ]
# At tau=rho with Im rho = sqrt(3)/2: 2 Im rho = sqrt(3).
# (2 Im rho)^{-3} = 1/(3 sqrt 3) = 1/(3^{3/2})
# (2 Im rho)^2 / 3 = 3/3 = 1
# So V_F(rho) = 1/(3 sqrt 3) [ |D_tau W(rho)|^2 - 3 |W(rho)|^2 ]
# Need D_tau W(rho) = W'(rho) + d_tau K (rho) W(rho)
# d_tau K(rho) = 3 i / (2 Im rho) = 3i/sqrt 3 = i sqrt 3.
# So D_tau W(rho) = W'(rho) + i sqrt 3 W(rho).

# W'(rho) numerical: finite difference
h = mp.mpf("1e-4")
Wp_rho = (W_full(rho + h) - W_full(rho - h))/(2*h)
print(f"W'(rho) ~ {Wp_rho}")

D_tau_W_rho = Wp_rho + 1j*sqrt3 * W_rho_num
print(f"D_tau W(rho) = {D_tau_W_rho}")
print(f"|D_tau W(rho)|^2 = {abs(D_tau_W_rho)**2}")

V_F_rho = (1/(3*sqrt3)) * (abs(D_tau_W_rho)**2 - 3 * abs(W_rho_num)**2)
print(f"V_F(rho) = {V_F_rho}")
if mp.re(V_F_rho) > 0:
    print(f"V_F(rho) > 0: rho is HIGHER ENERGY than i. tau=i is the GLOBAL MIN. ✓")
elif mp.re(V_F_rho) < 0:
    print(f"V_F(rho) < 0: rho is AdS, lower energy than i. Bad: tau=i is metastable.")
else:
    print(f"V_F(rho) ~ 0: degeneracy with tau=i. Bad: bridge fails.")
