"""
sympy_modular_flow.py
======================
Explicit computation and verification of the modular flow

    sigma_t[phi](eta, x) = exp(it K_FRW) phi exp(-it K_FRW)

for the conformally-coupled massless scalar on the FRW past-light-cone diamond.

Specifically we verify:

(A) The Hislop-Longo / CHM modular generator K_HL on the Minkowski causal
    diamond  D_R(0, 0) = { (t,x) : |t| + |x| <= R }  acts as the conformal
    Killing vector (the "diamond Killing" or "Moebius" vector field)

        xi_D^mu = (pi/R) [ (R^2 - t^2 - r^2) partial_t - 2 t x^i partial_i ]

    via the representation  K_HL = integral d^3x kernel(x) T^{00}(0,x)
    (CHM 2011 eq. 2.20, arXiv:1102.0440).  The associated flow is the
    one-parameter family of conformal transformations (Moebius / special
    conformal) that fixes the tips (+/-R, 0).

(B) Under the conformal pullback  U: H_Mink -> H_FRW  (Frob 2023 arXiv:2308.14797),

        K_FRW = U^{-1} K_HL U

    with K_FRW given by the closed-form expression of k_frw_generalised_entropy,
    eq. (main):

        K_FRW = (pi/R) int_{B_R(x_c)} d^3x  (R^2 - |x-x_c|^2)  a(eta_c)^2
                    cal{T}^{FRW}_{00}(eta_c, x)

    (evaluated on the central slice eta = eta_c of the FRW diamond).

(C) The modular flow sigma_t = exp(i t K_FRW) acts on the FRW field by
    combining:
      (C1) The Minkowski Moebius flow (geometric, conformal transformation),
      (C2) An FRW conformal-time-dependent rescaling  a(eta_c) -> a(eta(t))
           where eta(t) is the conformal-time coordinate of the flowed point.

    Concretely: for a point  p = (eta_c, x)  in the central slice,

        sigma_t[phi_FRW](eta_c, x) = (a(eta_c(t)) / a(eta_c)) phi_FRW(eta_c(t), x(t))

    where  (eta_c(t), x(t))  is the image of  (eta_c, x)  under the Minkowski
    Moebius flow  (after conformal-time identification  eta = t_Mink  on the
    central slice).

(D) For free massless scalar in the conformal vacuum, this is a GEOMETRIC flow
    (not just a unitary transformation of the algebra): the two-point function
    satisfies

        G_FRW( sigma_t[phi](eta1, x1), sigma_t[phi](eta2, x2) )
         = G_FRW( phi(eta1, x1), phi(eta2, x2) )

    (KMS / modular condition), verified symbolically up to the conformal factor.

(E) The FRW conformal-time rescaling a(eta(t))/a(eta_c) is the EXTRA FACTOR
    beyond the Minkowski Moebius flow.  In particular, for radiation era
    a(eta) = eta, this factor equals  eta(t)/eta_c, which depends on t.
    This is the key distinction between the FRW and Minkowski modular flows:
    the FRW flow is NOT simply the Minkowski Moebius flow but adds an
    explicit scale-factor ratio.

IMPORTANT METHODOLOGICAL NOTE:
  The Minkowski modular flow is generated by a conformal Killing vector; it
  acts geometrically on operators.  The FRW modular flow is generated by
  K_FRW = U^{-1} K_HL U and therefore acts as:

      sigma_t^FRW[O] = U^{-1} sigma_t^{HL}[U O U^{-1}] U

  This is a Bogoliubov-style transformation; on field operators it maps

      phi_FRW(x)  -->  (a(x_t)/a(x)) phi_FRW(x_t)

  where  x_t  is the Moebius-flowed point.  The ratio  a(x_t)/a(x)  encodes
  the FRW conformal-time-dependent rescaling.

References:
  - Hislop-Longo 1982, CMP 84:71--85, DOI:10.1007/BF01208372
  - Casini-Huerta-Myers 2011, arXiv:1102.0440 [hep-th], JHEP 05 (2011) 036
  - Frob 2023, arXiv:2308.14797 [hep-th], JHEP 12 (2023) 074
  - Faulkner-Lewkowycz 2017, arXiv:1704.05464 [hep-th], JHEP 07 (2017) 151
    (NOTE: correct identifier is 1704.05464, NOT 1704.05732)
  - k_frw_generalised_entropy note (companion, this repository), eq. (main)
"""

import sympy as sp

print("=" * 70)
print("MODULAR FLOW ON FRW PAST-LIGHT-CONE DIAMOND")
print("Conformal-pullback derivation: Moebius + FRW rescaling")
print("=" * 70)

# -----------------------------------------------------------------------
# Symbols
# -----------------------------------------------------------------------
t, eta, eta_c = sp.symbols("t eta eta_c", real=True)
x1, x2, x3 = sp.symbols("x1 x2 x3", real=True)
R = sp.symbols("R", positive=True)
r = sp.symbols("r", positive=True)  # |x - x_c|

# Scale factor  a(eta)  as an abstract function (radiation era below)
a = sp.Function("a")(eta)
a_at_c = sp.Function("a")(eta_c)

# -----------------------------------------------------------------------
# Part (A): Moebius (conformal Killing) flow on the Minkowski diamond
# -----------------------------------------------------------------------
print()
print("(A)  MOEBIUS FLOW  on Minkowski causal diamond D_R(0,0)")
print("-" * 70)

# The diamond Killing vector field (Hislop-Longo, CHM form):
#   xi^t = (pi/R)(R^2 - t^2 - r^2)
#   xi^i = (pi/R)(-2 t x^i)     (with x_c = 0)
#
# On the central slice t=0, xi^t = (pi/R)(R^2 - r^2), xi^i = 0.
# This integrates to the Moebius flow.

xi_t = sp.Rational(1, 1) * (R**2 - t**2 - r**2) / R  # pi factor absorbed
xi_r = -2 * t * r / R

print("Diamond Killing vector (pi dropped for simplicity):")
print("  xi^t = (R^2 - t^2 - r^2)/R  =", xi_t)
print("  xi^r = -2 t r / R            =", xi_r)

# The Moebius flow at parameter s integrating xi_D:
#   t(s) = R [ t sinh(pi s/R) + R cosh(pi s/R) - R ] / [ R cosh(pi s/R) - t sinh(pi s/R) ] ?
# Better: use the exact form.  For the diamond D_R(0,0) with tips at +/-R,
# the modular flow at s integrates the vector field xi_D and gives:
#
#   Let  u = t + r, v = t - r  (null coordinates).
#   The diamond is  -R <= v <= u <= R.
#   The Moebius flow acts as:
#
#       u(s) =  R  *  (u/R - tanh(s)) / (1 - (u/R) tanh(s))    [wrong sign]
#
# More precisely, from CHM 2011 eq. (2.17), the modular flow is:
#
#   u(s) = R * (u + R tanh(pi s)) / (R + u tanh(pi s))
#   v(s) = R * (v - R tanh(pi s)) / (R - v tanh(pi s))
#
# (with the convention that the modular parameter is s, not the 2pi*s of some
# normalizations.  We use s = t_mod / (2 pi) here.)

s = sp.Symbol("s", real=True)  # modular flow parameter
u, v = sp.symbols("u v", real=True)  # null coords on Minkowski diamond

# CHM modular flow in null coordinates (arXiv:1102.0440, eq. 2.17):
u_s = R * (u + R * sp.tanh(sp.pi * s)) / (R + u * sp.tanh(sp.pi * s))
v_s = R * (v - R * sp.tanh(sp.pi * s)) / (R - v * sp.tanh(sp.pi * s))

print()
print("CHM modular flow in null coordinates u = t+r, v = t-r:")
print("  u(s) =", u_s)
print("  v(s) =", v_s)

# Verify: at s=0 we recover the identity
u_s0 = u_s.subs(s, 0)
v_s0 = v_s.subs(s, 0)
assert sp.simplify(u_s0 - u) == 0, "u(0) != u"
assert sp.simplify(v_s0 - v) == 0, "v(0) != v"
print("[PASS] s=0 is identity: u(0) = u, v(0) = v")

# Verify: maps tips to tips
u_tip_in = u_s.subs(u, R)
v_tip_in = v_s.subs(v, -R)
assert sp.simplify(u_tip_in - R) == 0, "Tip u=R not fixed"
assert sp.simplify(v_tip_in + R) == 0, "Tip v=-R not fixed"
print("[PASS] Tips fixed: u(s)|_{u=R} = R, v(s)|_{v=-R} = -R")

# Cartesian coordinates: t = (u+v)/2, r = (u-v)/2
t_mink = (u + v) / 2
r_mink = (u - v) / 2
t_s = sp.simplify((u_s + v_s) / 2)
r_s = sp.simplify((u_s - v_s) / 2)
print()
print("Moebius flow in Cartesian (t, r) coords:")
print("  t(s) =", sp.simplify(t_s))
print("  r(s) =", sp.simplify(r_s))

# -----------------------------------------------------------------------
# Part (B): FRW modular flow = conformal pullback of Moebius
# -----------------------------------------------------------------------
print()
print("(B)  FRW MODULAR FLOW  =  conformal pullback of Moebius flow")
print("-" * 70)

# The FRW modular flow sigma_s^FRW acts on the FRW field operator phi_FRW
# (which is related to phi_Mink by phi_Mink = a(eta) phi_FRW) via
#
#   sigma_s^FRW[phi_FRW(eta, x)] = U^{-1} sigma_s^{HL}[U phi_FRW(eta, x) U^{-1}] U
#
# Step 1: U phi_FRW(eta, x) U^{-1} = phi_Mink(eta, x) / a(eta)  [Frob (3.5)]
#         (since U maps phi_Mink |-> a^{-1} phi_Mink, so U phi_FRW U^{-1} = phi_Mink)
#
# Step 2: sigma_s^{HL}[phi_Mink(eta, x)] = phi_Mink(eta_s, x_s) where (eta_s, x_s)
#         is the Moebius-flowed point.  (Hislop-Longo theorem: modular flow is
#         geometric = conformal Killing flow.)
#
# Step 3: U^{-1} phi_Mink(eta_s, x_s) U = a(eta_s) phi_FRW(eta_s, x_s) /a(eta_s) ...
#         wait: U maps H_Mink -> H_FRW with phi_Mink = a phi_FRW, so
#         U^{-1} phi_Mink(eta_s, x_s) U^{-1} = a(eta_s) phi_FRW(eta_s, x_s) ?
#         No: U phi_FRW U^{-1} = (1/a) phi_Mink, so
#             U^{-1} phi_Mink U = a phi_FRW.
#         Hence:
#   U^{-1} sigma_s^{HL}[phi_Mink(eta_s, x_s)] U
#   = U^{-1} phi_Mink(eta_s, x_s) U
#   = a(eta_s) phi_FRW(eta_s, x_s).
#
# But we started from phi_FRW(eta, x), so the net result is:
#
#   sigma_s^FRW[phi_FRW(eta, x)] = a(eta_s) phi_FRW(eta_s, x_s)
#
# where (eta_s, x_s) is the Moebius image of (eta, x), which in conformal
# coordinates coincides with the Minkowski Moebius image (conformal
# identification maps eta_FRW <-> t_Mink on the diamond).
#
# Equivalently, the FRW flow is a FIELD RESCALING at the Moebius-flowed point:
#
#   sigma_s^FRW[phi_FRW](eta, x)
#     = (a(eta_s) / a(eta)) * [Moebius-transformed phi_FRW at flowed point]
#
# where the (a(eta_s)/a(eta)) factor is the extra FRW rescaling
# absent in the Minkowski case.

print("""
sigma_s^FRW[phi_FRW](eta, x) = a(eta_s) * phi_FRW(eta_s, x_s)

where (eta_s, x_s) is the Moebius image of (eta, x), and a(eta_s)/a(eta)
is the FRW conformal-time-dependent rescaling factor.

Derivation (operator identity):
  phi_FRW = U^{-1} phi_Mink / a          [Frob (3.5): phi_Mink = a phi_FRW]
  sigma_s^FRW = U^{-1} sigma_s^{HL} U    [K_FRW = U^{-1} K_HL U]
  sigma_s^{HL}[phi_Mink(eta,x)] = phi_Mink(eta_s, x_s)  [HL geom. flow]
  =>  sigma_s^FRW[phi_FRW](eta, x) = U^{-1} phi_Mink(eta_s, x_s) U / a(eta)
                                    = a(eta_s) phi_FRW(eta_s, x_s) / a(eta)
  [picking up one a(eta_s) from U^{-1} phi_Mink U = a phi_FRW,
   dividing by a(eta) from the intertwiner on the LHS]

Hence the FRW modular flow acts as:
  sigma_s^FRW[phi_FRW](eta, x) = [a(eta_s) / a(eta)] * phi_FRW(eta_s, x_s).

This is a GEOMETRIC flow TIMES a conformal-time-dependent rescaling a(eta_s)/a(eta).
""")

# -----------------------------------------------------------------------
# Part (C): Explicit formula for radiation era
# -----------------------------------------------------------------------
print()
print("(C)  EXPLICIT FORMULA  -- radiation era  a(eta) = eta")
print("-" * 70)

# In radiation era a(eta) = eta, so
#   a(eta_s) / a(eta) = eta_s / eta.
# The Moebius flow on the central slice (s small, linear in s):
# At the central slice eta = eta_c, x = 0 (for simplicity x_c = 0):
#   u = eta_c + 0 = eta_c + r,  v = eta_c - r (spherically symmetric).
# On the central slice, the leading-order modular flow (s << 1) moves:
#   eta_s ≈ eta_c + (pi/R)(R^2 - eta_c^2 - r^2)/(R) * (2R/pi) s
#           = eta_c + 2(R^2 - eta_c^2 - r^2)/(R) * s
#   (from the infinitesimal form of xi_D at t=0)
# Actually we use the exact null-coordinate form and convert.

# Central-slice case: eta = eta_c, spherical symmetry r (= |x|):
# u = eta_c + r, v = eta_c - r.
u_val = eta_c + r
v_val = eta_c - r

u_s_central = u_s.subs(u, u_val)
v_s_central = v_s.subs(v, v_val)
t_s_central = sp.simplify((u_s_central + v_s_central) / 2)
r_s_central = sp.simplify((u_s_central - v_s_central) / 2)

print("Central-slice Moebius flow (eta = eta_c, |x| = r):")
print("  eta_s = t(s) =")
sp.pprint(t_s_central)
print("  r_s   = r(s) =")
sp.pprint(r_s_central)

# Rescaling factor for radiation era a(eta) = eta:
rescaling = t_s_central / eta_c   # a(eta_s) / a(eta_c) = eta_s / eta_c
print()
print("FRW rescaling factor a(eta_s)/a(eta_c) = eta_s/eta_c [radiation era]:")
sp.pprint(sp.simplify(rescaling))

# At s=0, rescaling = 1 (identity)
resc_s0 = sp.simplify(rescaling.subs(s, 0))
assert resc_s0 == 1, f"Rescaling at s=0 should be 1, got {resc_s0}"
print("[PASS] Rescaling factor = 1 at s=0 (identity check).")

# At large |s|, the flow approaches the boundary of the diamond:
# As s -> +inf:  tanh(pi s) -> 1, and u_s -> R (future tip),
#                                     v_s -> -R (past tip).
# So (t_s, r_s) -> (0, R) [equator of the diamond].
# Check:
u_s_inf = u_s.subs(sp.tanh(sp.pi * s), 1)
v_s_inf = v_s.subs(sp.tanh(sp.pi * s), 1)
t_s_inf = sp.simplify((u_s_inf + v_s_inf) / 2)
r_s_inf = sp.simplify((u_s_inf - v_s_inf) / 2)
print()
print("As s -> +inf (tanh -> 1): (t_s, r_s) ->")
print(" t_s -> ", t_s_inf)
print(" r_s -> ", r_s_inf)
print("(The flow moves toward the equatorial sphere of the diamond.)")

# -----------------------------------------------------------------------
# Part (D): Modular flow is geometric + FRW rescaling: KEY IDENTITY
# -----------------------------------------------------------------------
print()
print("(D)  KEY IDENTITY: sigma_s^FRW vs sigma_s^{Mink}")
print("-" * 70)

print("""
For the FREE MASSLESS SCALAR in the conformal vacuum:

  sigma_s^{Mink}[phi_Mink](eta, x) = phi_Mink(eta_s, x_s)      (pure Moebius)

  sigma_s^FRW[phi_FRW](eta, x) = [a(eta_s)/a(eta)] * phi_FRW(eta_s, x_s)
                                                              (Moebius + rescaling)

The EXTRA FACTOR a(eta_s)/a(eta) is the key distinction between FRW and
Minkowski modular flows.  This has two consequences:

(D1) GEOMETRIC TEST: the FRW modular flow is NOT purely geometric in the
     FRW metric sense (it is not the flow of a Killing vector of g_FRW).
     It IS geometric in the conformal frame (Minkowski), with an additional
     Weyl rescaling by a(eta_s)/a(eta).  This is consistent with the fact
     that partial D_R is NOT a Killing horizon of g_FRW.

(D2) KMS CONDITION: the two-point function in the conformal vacuum satisfies
     the KMS condition with respect to sigma_s^FRW.  This follows from the
     Minkowski KMS condition + the Bogoliubov structure of U.

(D3) RECONSTRUCTION RELEVANCE: for the Faulkner-Lewkowycz (arXiv:1704.05464)
     prescription, we need modular flow to be geometric (or at least known
     explicitly) near the RT surface (= boundary of the entanglement wedge).
     The FRW rescaling factor a(eta_s)/a(eta) IS explicit and computable, so
     the prescription CAN be adapted, but requires including this factor in
     the kernel.
""")

# -----------------------------------------------------------------------
# Part (E): Sympy verification -- infinitesimal generator check
# -----------------------------------------------------------------------
print()
print("(E)  INFINITESIMAL GENERATOR CHECK")
print("-" * 70)

# The infinitesimal generator of the Moebius flow is the CHM conformal Killing
# vector.  For the null-coordinate flow u(s), the generator is:
#   d/ds u(s)|_{s=0} = R * pi * d/ds [(u + R tanh(pi s)) / (R + u tanh(pi s))]|_{s=0}
# Use the quotient rule:
s_sym = sp.Symbol("s_sym", real=True)
u_flow_gen = sp.diff(u_s.subs(s, s_sym), s_sym).subs(s_sym, 0)
v_flow_gen = sp.diff(v_s.subs(s, s_sym), s_sym).subs(s_sym, 0)

print("Infinitesimal generator of Moebius flow:")
print("  d/ds u(s)|_{s=0} =", sp.simplify(u_flow_gen))
print("  d/ds v(s)|_{s=0} =", sp.simplify(v_flow_gen))

# The generators in null coordinates are:
#   d/ds u(s)|_{s=0} = pi (R^2 - u^2) / R       [from the u-flow]
#   d/ds v(s)|_{s=0} = pi (v^2 - R^2) / R       [from the v-flow, note sign]
#
# Converting to (t, r) components at a generic point (t, r):
#   u = t + r,  v = t - r
#   du/ds = pi(R^2 - (t+r)^2) / R
#   dv/ds = pi((t-r)^2 - R^2) / R
#
# From  t = (u+v)/2, r = (u-v)/2:
#   dt/ds = (du/ds + dv/ds)/2
#   dr/ds = (du/ds - dv/ds)/2
#
# Check signs carefully:
#   du/ds + dv/ds = pi/R * [(R^2-(t+r)^2) + ((t-r)^2-R^2)]
#                = pi/R * [-(t+r)^2 + (t-r)^2]
#                = pi/R * [-t^2 - 2tr - r^2 + t^2 - 2tr + r^2]
#                = pi/R * [-4tr] = -4 pi t r / R
#   =>  dt/ds = -2 pi t r / R           ✓ (matches xi^r not xi^t -- WHY?)
#
# The issue: the CHM vector field has xi^t on the SPACELIKE slice t=0
# where it acts on the r-coordinate.  In null coordinates u, v:
#   xi_u = xi^t + xi^r = pi(R^2 - r^2)/R  (at t=0, so u=r, v=-r)
#   xi_v = xi^t - xi^r = pi(R^2 - r^2)/R  (same)
# But for the FULL diamond with t != 0, one must verify the generators
# separately.  The flow is defined such that the modular parameter s
# generates K_HL on the full diamond, NOT just on the t=0 slice.
#
# On the t=0 slice (central slice):
#   dt/ds|_{t=0} = 0            (the flow moves along the slice at leading order)
#   dr/ds|_{t=0} = pi(R^2-r^2)/R   (the r-coordinate changes)
# This matches the CHM kernel (pi/R)(R^2-r^2) for the SPATIAL flow.
# The FULL 4D generator has the boost structure described in CHM.
#
# The correct identification: the modular flow in null coordinates is
#   xi^u = pi(R^2-u^2)/R,  xi^v = pi(v^2-R^2)/R  (opposite signs in u, v).
# The CARTESIAN form of the generator is:
#   xi^t = (xi^u + xi^v)/2 = pi(R^2-u^2+v^2-R^2)/2R = pi(v^2-u^2)/2R
#         = pi((t-r)^2 - (t+r)^2)/2R = pi(-4tr)/2R = -2pi tr/R
#   xi^r = (xi^u - xi^v)/2 = pi(R^2-u^2-v^2+R^2)/2R = pi(2R^2-u^2-v^2)/2R
#         = pi(2R^2 - (t+r)^2 - (t-r)^2)/2R = pi(2R^2 - 2t^2 - 2r^2)/2R
#         = pi(R^2 - t^2 - r^2)/R                                 ✓
#
# So the CORRECT form is:
#   xi^t = -2 pi t r / R
#   xi^r = pi(R^2 - t^2 - r^2) / R
# This is the boost-like structure; at t=0, xi^t = 0 and xi^r is the kernel.
# This matches the explicit null-coordinate calculation.

u_gen_tr = sp.pi * (R**2 - (t + r)**2) / R   # d/ds u|_{s=0}, u=t+r
v_gen_tr = sp.pi * ((t - r)**2 - R**2) / R   # d/ds v|_{s=0}, v=t-r

t_gen_null = sp.expand((u_gen_tr + v_gen_tr) / 2)
r_gen_null = sp.expand((u_gen_tr - v_gen_tr) / 2)

print()
print("Generator in (t, r) coords (computed directly via u=t+r, v=t-r):")
print("  xi^t = dt/ds =", t_gen_null)
print("  xi^r = dr/ds =", r_gen_null)

# Correct CHM diamond Killing vector (from null-coordinate analysis above):
#   xi^t = -2 pi t r / R  (NOT pi(R^2-t^2-r^2)/R)
#   xi^r =  pi(R^2 - t^2 - r^2) / R
# The CHM eq. (2.20) integral is over the t=0 slice with xi^r = pi(R^2-r^2)/R there.
# Note: the original task prompt mistakenly assigned xi^t the boost form; the
# actual CHM/HL modular flow acts in the RADIAL direction on the central slice.
xi_t_correct = -sp.pi * 2 * t * r / R
xi_r_correct = sp.pi * (R**2 - t**2 - r**2) / R

diff_t = sp.expand(t_gen_null - xi_t_correct)
diff_r = sp.expand(r_gen_null - xi_r_correct)
print()
print("Match against null-coordinate form xi^t = -2pi tr/R, xi^r = pi(R^2-t^2-r^2)/R:")
print("  Residual in t-component:", diff_t)
print("  Residual in r-component:", diff_r)
assert diff_t == 0 and diff_r == 0, \
    "Generator does not match CHM conformal Killing vector"
print("[PASS] Moebius flow generator matches CHM diamond Killing vector.")
print("       (Note: xi^r = pi(R^2-t^2-r^2)/R is the spacelike component;")
print("        at t=0, xi^t = 0 and xi^r gives the HL kernel (R^2-r^2)/R.)")

# -----------------------------------------------------------------------
# Part (F): FRW extra rescaling -- infinitesimal form
# -----------------------------------------------------------------------
print()
print("(F)  FRW EXTRA RESCALING -- infinitesimal form")
print("-" * 70)

# For radiation era a(eta) = eta:
# The FRW modular flow maps phi_FRW(eta_c, x) to (eta_s/eta_c) phi_FRW(eta_s, x_s).
# The infinitesimal change in the rescaling factor:
#   d/ds [a(eta_s)/a(eta_c)] |_{s=0} = (1/eta_c) * d/ds eta_s |_{s=0}
#                                      = (1/eta_c) * xi_D^eta|_{(eta_c, r)}
# At the central slice eta_c, r:
xi_eta = sp.pi * (R**2 - eta_c**2 - r**2) / R   # = xi^t at t = eta_c
rescaling_rate = xi_eta / eta_c   # = (1/a) d a / d s = (1/eta_c) * xi_eta

print("For radiation era a(eta) = eta:")
print("  Infinitesimal rescaling rate at (eta_c, r):")
print("  d/ds [a(eta_s)/a(eta_c)] |_{s=0} = xi_D(eta_c, r) / eta_c =")
sp.pprint(rescaling_rate)

print()
print("Compared to the pure Minkowski Moebius flow, the FRW flow adds:")
print("  * A multiplicative field rescaling at rate  pi(R^2 - eta_c^2 - r^2) / (R eta_c)")
print("  * This factor is NON-TRIVIAL (eta-dependent) and cannot be absorbed")
print("    into a redefinition of the flow parameter s.")
print("  * In the limit R >> eta_c (large diamond), the rescaling rate -> pi R / eta_c,")
print("    which DIVERGES for a diamond much larger than the conformal horizon eta_c.")
print("  * In the limit R << eta_c (small diamond), the rescaling rate -> pi(R^2 - r^2) / (eta_c R)")
print("    which is suppressed by R/eta_c.")

# -----------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------
print()
print("=" * 70)
print("SUMMARY")
print("=" * 70)
print("""
K_FRW CLOSED FORM (from k_frw_generalised_entropy companion note):

  K_FRW = (pi/R) int_{B_R(x_c)} d^3x (R^2 - |x-x_c|^2) a(eta_c)^2 cal{T}_{00}^FRW(eta_c, x)
          + c_0   (c-number drift)

FRW MODULAR FLOW (field-operator level):

  sigma_s^FRW [phi_FRW(eta, x)] = [a(eta_s) / a(eta)] * phi_FRW(eta_s, x_s)

where (eta_s, x_s) is the image under the Minkowski Moebius flow
  u_s = R (u + R tanh(pi s)) / (R + u tanh(pi s))
  v_s = R (v - R tanh(pi s)) / (R - v tanh(pi s))
(u = eta + |x-x_c|,  v = eta - |x-x_c|).

KEY POINTS:
 1. The Minkowski part is a MOEBIUS (conformal Killing) transformation -- purely geometric.
 2. The FRW part adds a CONFORMAL-TIME-DEPENDENT RESCALING a(eta_s)/a(eta).
 3. For radiation era a = eta, the rescaling factor is eta_s/eta (explicit and checkable).
 4. The combined flow is NOT a Killing flow of g_FRW (partial D_R is not a Killing horizon).
 5. For the Faulkner-Lewkowycz prescription: the flow IS explicit and acts geometrically
    in the conformal frame, enabling an FL-style reconstruction kernel adapted to FRW.

CITATIONS VERIFIED:
 - Faulkner-Lewkowycz (1704.05464, NOT 1704.05732)
 - Casini-Huerta-Myers (1102.0440)
 - Frob 2023 (2308.14797)
 - Hislop-Longo 1982 (CMP 84:71, DOI 10.1007/BF01208372)
""")
