"""
Analysis of PARI/GP computed Frobenius traces on Fermat quartic K3.

Note: Fermat quartic has Picard rank 20 over algebraically closed field of char 0,
so 20 of the 22 eigenvalues of Frob on H^2 are algebraic units * p.
Singular fibers at p with p^2 ≡ -1 (mod 4) or related conditions give special behavior.

For Fermat quartic, bad reduction at p=2 only.
Picard rank 20 + Tate twists -> Tr(Frob) decomposition into algebraic and transcendental parts.

a_p data from PARI:
"""

import numpy as np
from sympy import sieve, isprime
from math import gcd, sqrt

# From PARI computation
data = [
    (3, 16, 6),
    (5, 0, -26),
    (7, 64, 14),
    (11, 144, 22),
    (13, 128, -42),
    (17, 600, 310),
    (19, 400, 38),
    (23, 576, 46),
    (29, 768, -74),
]

print("="*70)
print("Fermat quartic K3: x^4+y^4+z^4+w^4=0, Frobenius traces")
print("="*70)
print(f"{'p':<4} {'#X(F_p)':<10} {'Tr(Frob|H^2)':<14} {'Tr/p':<12} {'Tr/22p':<12} {'mod p?'}")
for p, n, tr in data:
    print(f"{p:<4} {n:<10} {tr:<14} {tr/p:<12.4f} {tr/(22*p):<12.4f} {tr % p:<6}")

print()
print("="*70)
print("STRUCTURE: For p mod something, Tr/p is integer or non-integer?")
print("="*70)
# pattern: p=3,7,11,19,23 -> Tr/p = 2 exactly. p=5,13,17,29 -> non-integer (mod different)
# Fermat quartic over F_p: Tr depends on Galois orbit structure on Picard
# p≡3 mod 4: x^4=-1 has solutions iff 4|(p-1), so 4 NOT divide (p-1)
# Equivalently, p≡3 (mod 4) means x^4 surjects but is NOT bijection
print("p, p mod 4, p mod 8, Tr/p")
for p, n, tr in data:
    print(f"  p={p:<3}  p%4={p%4}  p%8={p%8}  Tr/p={tr/p}")

print()
print("Pattern is clear:")
print("  p ≡ 3 (mod 4): Tr/p = 2 exactly (5/9 primes)")
print("  p ≡ 1 (mod 4): Tr/p generally non-integer")
print()

# Key insight: For Fermat quartic with x^4 map, structure depends on
# whether F_p contains 4th roots of unity (mu_4 ⊂ F_p iff p ≡ 1 mod 4)

# Now test ECI hypotheses
print("="*70)
print("H1 TEST: Does ECI Σ premiers = 281 (Λ exponent) appear in Frobenius?")
print("="*70)
# Sum of first 14 primes
primes_14 = list(sieve.primerange(2, 50))[:14]
sum_14 = sum(primes_14)
print(f"First 14 primes: {primes_14}")
print(f"Sum = {sum_14}")
print()

# Try various combinations of Frobenius traces
traces = [t for p, n, t in data]
abs_traces = [abs(t) for t in traces]
ps = [p for p, n, t in data]
print(f"Frobenius traces: {traces}")
print(f"Abs traces: {abs_traces}")
print(f"Sum abs traces (p=3..29): {sum(abs_traces)}")
print(f"Sum traces (p=3..29): {sum(traces)}")
print(f"Sum |Tr|/p: {sum(abs(t)/p for p, n, t in data):.3f}")
print(f"Sum (#X(F_p) - 1 - p^2): {sum(t for p,n,t in data)} (same as sum traces)")
print()
print(f"Target 281 (Λ exponent): comparable? sum=300, abs sum=578, neither matches 281.")
print()

# Test: Are there individual Tr(Frob) values matching primes?
print("Match individual |Tr| to primes:")
primes_list = list(sieve.primerange(2, 100))
for p, n, tr in data:
    closest_prime = min(primes_list, key=lambda q: abs(q - abs(tr)))
    print(f"  p={p}, |Tr|={abs(tr)}, closest prime={closest_prime} ({abs(closest_prime - abs(tr))})")

print()
print("="*70)
print("Sato-Tate distribution check (random model):")
print("="*70)
# For K3, Sato-Tate: a_p/p uniform on [-22, +22] ideally? Not quite,
# but |a_p| <= 22*p (Weil), and central limit ~ N(0, c*p) for transcendental part
# For Fermat quartic with rho_geom=20, only 2-dim transcendental.
# So Tr(Frob|trans) bounded by 2p, and Tr(Frob|alg part) = 20*p * (algebraic)
# This explains why Tr/p ≈ 2 in many cases (= 20 from Picard contribution / 10 = 2?)

# Let me think again: H^2 = 22 dim, Picard part 20 dim (over Q_l), transcendental 2 dim.
# Frob on Picard part = ±p with multiplicities (since Picard generated by (-1) curves -> eigenvalue +p?)
# Actually Tr(Frob | NS) = (rank of NS that's Frob-invariant) * p + complicated stuff
# This is where it gets technical.

# Empirical observation: Tr/p = 2 for many primes suggests
# Tr(Frob|H^2) = 2p (from -2 = self-intersection of canonical?) + traceless part = small.
# This is geometrically: Picard rank Galois fixed = 2 generically?

# 22 = b_2(K3) and we have 22 eigenvalues. p=3: Tr=6=2p. p=7: Tr=14=2p. Suggests
# rank of NS^Frob = 2 generically (the hyperplane class and one Hodge class).

print()
print("INTERPRETATION (preliminary):")
print(" - For p ≡ 3 mod 4: Tr = 2p exactly = 2·(eigenvalue p, multiplicity 2)")
print("   => Suggests generic Picard^Frob rank = 2 (hyperplane class + Cinépair?)")
print(" - For p ≡ 1 mod 4 (5, 13, 17, 29): Tr ≠ 2p")
print("   => Extra Picard cycles when p ≡ 1 mod 4 (mu_4 ⊂ F_p)")
print()

# Test: For p ≡ 1 mod 4, is there extra Picard rank?
# Fermat quartic in P^3 has Aut group of order 4! * 4^3 / 4 = etc.
# It's known that Fermat quartic has all 20 Picard cycles defined over Q(zeta_8)

print("="*70)
print("Now compare with ECI labeling hypothesis (primes ↔ Lie generators)")
print("="*70)

# ECI hypothesis: generators of SU(N) <-> first N^2-1 primes
# Test: Does the Frobenius eigenvalue spectrum reproduce primes for small N?
# For SU(3) [dim 8], we'd want 8 eigenvalues matching first 8 primes 2,3,5,7,11,13,17,19

# Frobenius eigenvalues on H^2 of K3: 22 numbers each of magnitude p
# If we factor out p, we have 22 algebraic numbers of magnitude 1 = roots of unity
# (for CM K3) or generic Weil numbers.

# For Fermat quartic: Hodge structure has 20 Picard cycles + 2 transcendental
# CM by Q(zeta_8) (degree 4 over Q)

# Question: Do these 22 algebraic numbers, after some standardization,
# correspond to primes (2, 3, 5, 7, 11, 13, 17, 19, 23, ...) ?

# Algebraic numbers of magnitude 1 are roots of unity (Kronecker theorem)
# OR real algebraic numbers in (-1, 1) -- but those have |·| < 1, contradiction
# Wait: algebraic of magnitude 1 = sum of (zeta + 1/zeta) etc., real numbers in [-2, 2]
# So the trace eigenvalues / p ∈ [-2, 2] (Lehmer / Sato-Tate)

# For 22-dim, sum of 22 things in [-1,1] each = Tr/p ∈ [-22, 22]
# Observed Tr/p: 2, -5.2, 2, 2, -3.2, 18.2, 2, 2, -2.55
# All within [-22, 22] ✓
# But p=17 case: 18.2 = very high, suggests SUSPECT bad reduction!

print("CRITICAL: p=17 gives Tr/p = 18.24, very close to upper bound 22.")
print("This is suspect -- check if 17 is bad reduction or if computation is wrong.")
print()

# Check bad reduction: for Fermat quartic x^4+y^4+z^4+w^4=0,
# bad primes are p|disc(form). For diagonal quartic, bad primes = {2}.
# So p=17 should be GOOD. Then Tr/p = 18.2 is unusual.

# Let me double-check: #X(F_17) = 600.
# Expected #X ≈ 1 + p^2 + Tr ≈ 1 + 289 + Tr = 290 + Tr.
# If Tr ≈ 0, expected 290. Got 600 => Tr = 310. So yes, anomalous.

# Fermat quartic over F_17 may have special structure (17 ≡ 1 mod 4 ⇒ extra autos)
# Also 4 | (17-1), so x^4=a has 4 solutions when a is 4th power, else 0
# This greatly inflates #X(F_17) by allowing more solutions to combine.

# OK so this is NOT spurious -- it's that the L-function of Fermat quartic
# factors heavily due to CM structure, and at p≡1 mod 4 the Frobenius is
# diagonal with many large eigenvalues.

print("p=17 anomaly is GENUINE: 17 ≡ 1 mod 4 means F_17 contains mu_4,")
print("so Fermat quartic acquires extra Picard cycles over F_17.")
print("Tr is large because many algebraic eigenvalues = +p (not -p).")
print()
