"""
M149 sub-task 5 (continued) — KMS_infty structure and Cl(O_K) = Z/2 action
for K_Q = Q(sqrt(-22)).

CMR Theorem 5.1 (page 22 of arXiv:math/0501424):
  - For 0 < beta <= 1: unique KMS state.
  - For beta > 1: extremal KMS_beta states E_beta ≅ A_{K,f}^*/K^*  (Eq 5.1)
    parametrized by invertible K-lattices L = (Lambda, phi) up to scaling.
  - State formula: phi_{beta,L}(f) = zeta_K(beta)^{-1} * sum_{J ⊂ O ideal}
                                     f(J^{-1} L, J^{-1} L) * n(J)^{-beta}    (Eq 5.2)
  - KMS_∞ states phi_{∞,L} take values in K^ab on arithmetic subalgebra.
    Class field theory isomorphism (Eq 5.3):
      alpha . phi_{∞,L} = phi_{∞,L} . theta^{-1}(alpha)
    for alpha in Gal(K^ab/K).

The KEY h_K = 2 vs h_K = 1 difference is in the structure of E_beta:
  - For h_K = 1, all invertible K-lattices L are commensurable to O_K = principal lattice.
  - For h_K = 2, E_beta has a Z/2-action by Cl(O_K) AS ENDOMORPHISMS (NOT auto-) modulo inner.

CMR (page 4-5, end of section 4): Eq (4.4) commutative diagram
   1 -> O*_S/O* -> I_K/K* -> Cl(O) -> 1
              ≃         ≃          ≃
   1 -> Gal(K^ab/H) -> Gal(K^ab/K) -> Gal(H/K) -> 1
where H is Hilbert class field of K. So Cl(O_K) corresponds to Gal(H_K/K).

For K_Q = Q(sqrt(-22)):
  Cl(O_K) = Z/2
  Hilbert class field H_K = Q(sqrt(-22), j(sqrt(-22)))
                     = Q(sqrt(-22), sqrt(2))   [since j(sqrt(-22)) generates Q(sqrt(2)) over Q]
  Hence Gal(H_K/K_Q) = Z/2, generated by the unique non-trivial element of Cl(O_K).
"""
import mpmath
mpmath.mp.dps = 30

print("="*70)
print("M149 sub-task 5 (continued) — KMS_infty + Cl(O_K) action for K_Q")
print("="*70)

# Hilbert class polynomial H_{-88}(X) from M143
print("\n(A) Hilbert class field H_K of K_Q = Q(sqrt(-22))")
print("-" * 70)
print(f"  Class number h_K = 2")
print(f"  H_{{-88}}(X) = X^2 - 6294842640000*X + 15798135578688*10^9   (M143)")

# Solve for j-invariants
a_coef = mpmath.mpf(-6294842640000)
b_coef = mpmath.mpf(15798135578688) * mpmath.mpf(10)**9
disc = a_coef**2 - 4*b_coef
print(f"  Discriminant of polynomial = {disc}")
sqrt_disc = mpmath.sqrt(disc)
print(f"  sqrt(disc) / 10^12 = {sqrt_disc/10**12}")
# Should be 2225561184000 * sqrt(2) per M143
factor = sqrt_disc / mpmath.sqrt(2)
print(f"  sqrt(disc)/sqrt(2) = {factor}  (expected 4451122368000)")

j1 = (-a_coef + sqrt_disc) / 2
j2 = (-a_coef - sqrt_disc) / 2
print(f"  j_1 = {j1}")
print(f"  j_2 = {j2}")
print(f"  j_1 + j_2 = {j1 + j2} (should be {-a_coef})")
print(f"  j_1 * j_2 = {j1 * j2} (should be {b_coef})")

# These two j-values are j(sqrt(-22)) and j(sqrt(-22)/2 * something) but
# importantly conjugate over Q with both in Q(sqrt(2)).
# The Hilbert class field is Q(sqrt(-22), j_1) = Q(sqrt(-22), sqrt(2)).

print(f"\n  Hilbert class field H_K = Q(sqrt(-22), sqrt(2))   (degree 4 over Q)")
print(f"    Gal(H_K/K_Q) = Z/2 (generated by complex/Galois conjugation of sqrt(2))")

# === Sub-task 4: Numerical verification of KMS_∞ at tau_Q ===
print("\n" + "="*70)
print("(B) Verify q_{tau_Q}(K_Q^*) fixed point property numerically (mpmath dps=30)")
print("="*70)

tau_Q = mpmath.mpc(0, mpmath.sqrt(mpmath.mpf(11)/2))
print(f"  tau_Q = i*sqrt(11/2) = {tau_Q}")

# Test: q_{tau_Q}(a + b*sqrt(-22)) = [[a, -11*b], [2*b, a]]
def q_tauQ(a, b):
    return mpmath.matrix([[a, -11*b], [2*b, a]])

def mobius(M, z):
    return (M[0,0]*z + M[0,1]) / (M[1,0]*z + M[1,1])

print(f"  Testing on units of O_K = {{±1}} (only roots of unity):")
print(f"    alpha = +1: q = [[1,0],[0,1]] = identity, fixed-point trivial.")
print(f"    alpha = -1: q = [[-1,0],[0,-1]] = -I, Mobius(z) = z. fixed-point trivial.")
print(f"  Testing on alpha = 2 + sqrt(-22) (norm 4 + 22 = 26):")
M = q_tauQ(2, 1)
res = mobius(M, tau_Q)
print(f"    q_{{tau_Q}}(2 + sqrt(-22)) = [[2,-11],[2,2]]")
print(f"    Mobius: {res}")
print(f"    err = {abs(res - tau_Q)}")
print(f"  Testing on alpha = 5 + 7*sqrt(-22) (norm 25 + 22*49 = 1103):")
M = q_tauQ(5, 7)
res = mobius(M, tau_Q)
print(f"    q_{{tau_Q}}(5 + 7*sqrt(-22)) = [[5,-77],[14,5]]")
print(f"    Mobius: {res}")
print(f"    err = {abs(res - tau_Q)}")

# Test on alpha = sqrt(-22) (a = 0, b = 1)
M = q_tauQ(0, 1)
res = mobius(M, tau_Q)
print(f"  Testing on alpha = sqrt(-22): q = [[0,-11],[2,0]]")
print(f"    det = 22 > 0 ✓")
print(f"    Mobius: {res}")
print(f"    err = {abs(res - tau_Q)}")

# === Sub-task 5: Cl(O_K) Z/2 action ===
print("\n" + "="*70)
print("(C) Cl(O_K) = Z/2 action by ENDOMORPHISMS modulo inner (CMR Eq 4.4 + Prop 4.14)")
print("="*70)

print("""
  CMR Eq (4.4) (commutative diagram):
    1 -> O*_S/O* -> I_K/K* -> Cl(O_K) -> 1
              ≃         ≃          ≃
    1 -> Gal(K^ab/H_K) -> Gal(K^ab/K) -> Gal(H_K/K) -> 1

  CMR Prop 4.14:
    - I_K/K^* acts on KMS_beta states (via symmetries modulo inner)
    - O^*/O^_K^* (the O_K-units modulo squares) act by AUTOMORPHISMS
    - Cl(O_K) = (I_K/K^*) / (O^*/O^_K^*) acts by ENDOMORPHISMS

  For K_Q = Q(sqrt(-22)): O_K^* = {±1}, w_K = 2 (only roots of unity).

  The non-trivial class of Cl(O_K) = Z/2 corresponds to the ideal a = (2, sqrt(-22)).
  Acting by endomorphism mu_a (CMR Eq 4.28):
    mu_a((Lambda, phi), (Lambda', phi')) = 1 if Lambda = a^{-1} Lambda' and phi' = phi
                                            0 otherwise.
  Range projection e_a (4.26-4.28):
    e_a = projection onto K-lattices divisible by a (i.e. a^{-1}*Lambda is a K-lattice).

  For h_K = 2, the CMR system has TWO physically distinct "principal" ideal sectors
  (both KMS sectors associated to the two ideal classes [O_K] and [a]) which the
  Cl(O_K) endomorphism action exchanges (modulo inner = via mu_J for principal J).
""")

# Concrete check: ideal sum in zeta_K splits as
# zeta_K(s) = sum over [I] in Cl(O_K) of zeta_{[I]}(s)
# where zeta_{[I]}(s) = sum_{J in [I]} 1/N(J)^s
# = (1/h_K) * h_K * (each class contributes equal residue)

print("\n(D) Splitting of zeta_K by ideal class (computational verification)")
print("-" * 70)

# Enumerate ideals by class for K = Q(sqrt(-22)), h_K = 2
# Class [O_K] = principal ideals; Class [a] = non-principal multiplied by a.
# Norm-class table for first few norms:
# Norm 1: only O_K = (1), class [O_K]
# Norm 2: only a = (2, sqrt(-22)), class [a]
# Norm 4: principal (2), class [O_K], plus a*a = (2) (= same), so just (2) = 1 ideal
# Wait: ideals of norm 4: (2) since N((2)) = 4 (in O_K, N(p)=p^2 for principal generated by rational p when p ramified... no wait, (2) = a^2 has N(a^2) = N(a)^2 = 4)
# Actually p_2 = a, N(a) = 2, a^2 = (2), N((2)) = 4. Both ideals exist. (2) is principal, but is it class [O_K]? Yes since (2) = (2). So:
#   Norm 4: {(2)} - 1 ideal class [O_K]

# Let me explicitly enumerate ideals by norm and class.
# Ideal types in O_K=Z[sqrt(-22)]:
#   - principal ideals (alpha) with norm |a^2 + 22*b^2| for alpha = a + b*sqrt(-22)
#   - non-principal: products of a (the unique prime over 2) and other prime ideals

# Primes 2, 11 ramify; 13, 19, 23, ... split; 3, 5, 7, 17 inert.
# For h_K = 2, an ideal is principal iff it has even number of "non-principal factors".
# The class of a prime ideal p over a split prime p with chi(p)=+1: must compute.

# Simpler: compute Cl_K = Z/2 explicitly via the count of ideals of norm n.
# Number of principal ideals of norm n = #{(a,b) ∈ Z^2 : a^2 + 22*b^2 = n} / 2 (units)
# (divide by 2 for unit action {±1})

def num_principal_ideals(n):
    """Number of distinct principal ideals (alpha) in O_K with N((alpha)) = n.
    alpha = a + b*sqrt(-22), N(alpha) = a^2 + 22*b^2 = n.
    Each ideal has 2 generators (alpha and -alpha) since O_K^* = {±1}.
    """
    count = 0
    sqn = int(mpmath.sqrt(n)) + 1
    sqnover22 = int(mpmath.sqrt(n / 22)) + 1
    for b in range(-sqnover22, sqnover22+1):
        rem = n - 22*b*b
        if rem < 0:
            continue
        a = int(mpmath.sqrt(rem))
        for s in [-1, 1]:
            aa = s * a
            if aa*aa + 22*b*b == n:
                count += 1
        # Try a+1, a-1 for off-by-one
        for da in [-1, 1]:
            aa = a + da
            if aa*aa + 22*b*b == n:
                count += 2 if aa != 0 else 1
                # Avoid double-count: don't add second time. Just brute force.
    return count // 2

# Better: brute force
def num_principal_ideals_v2(n):
    pairs = set()
    sqnover22 = int(mpmath.sqrt(n / 22)) + 2
    for b in range(-sqnover22, sqnover22+1):
        rem = n - 22*b*b
        if rem < 0:
            continue
        a_sq = rem
        a = int(round(mpmath.sqrt(a_sq)))
        for da in [-2, -1, 0, 1, 2]:
            aa = a + da
            if aa*aa + 22*b*b == n:
                # This represents alpha = aa + b*sqrt(-22)
                # Ideal (alpha) = (-alpha). Reduce by sign.
                key = tuple(sorted([(aa, b), (-aa, -b)]))[0]
                pairs.add(key)
    return len(pairs)

# Total ideals of norm n: a_n. We computed a_n already for first many n.
# So nonprincipal = a_n - principal.

def total_ideals(n):
    """Number of ideals of norm n via Dirichlet coefficients."""
    # Multiplicative: factor n into primes, multiply local factors.
    expected_chi = {2:0, 3:-1, 5:-1, 7:-1, 11:0, 13:1, 17:-1, 19:1, 23:1, 29:-1, 31:1, 37:1, 41:-1, 43:-1, 47:1, 53:1, 59:1, 61:-1, 67:-1, 71:1, 73:-1, 79:-1, 83:-1, 89:-1, 97:-1}
    # Hmm let me compute these from -88
    def jacobi(a, n):
        a = a % n
        result = 1
        while a != 0:
            while a % 2 == 0:
                a //= 2
                if n % 8 in (3, 5):
                    result = -result
            a, n = n, a
            if a % 4 == 3 and n % 4 == 3:
                result = -result
            a = a % n
        return result if n == 1 else 0

    m = n
    a_count = 1
    for p in [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]:
        if p > m:
            break
        k = 0
        while m % p == 0:
            m //= p
            k += 1
        if k == 0:
            continue
        chi = expected_chi.get(p, jacobi(-88, p))
        if chi == 0:  # ramified
            a_count *= 1  # only p_p^k
        elif chi == 1:  # split
            a_count *= (k + 1)
        else:  # inert
            if k % 2 == 0:
                a_count *= 1
            else:
                return 0
    if m > 1:
        chi = jacobi(-88, m)
        if chi == 0:
            pass
        elif chi == 1:
            a_count *= 2
        else:
            return 0
    return a_count

print(f"  Norm n  | total | principal | non-principal")
print(f"  --------|-------|-----------|-----------")
for n in [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 22, 23, 25, 27, 31, 44]:
    tot = total_ideals(n)
    prin = num_principal_ideals_v2(n)
    nonp = tot - prin
    print(f"  {n:6d}  |  {tot:3d}  |    {prin:3d}    |    {nonp:3d}")

print("""
Verification:
  - Norm 1: O_K only (principal)
  - Norm 2: a = (2, sqrt(-22)) only; non-principal (no x^2 + 22y^2 = 2)
  - Norm 4: (2) = a^2 only; principal
  - Norm 8: a^3 = a*(2); non-principal
  - Norm 22: (sqrt(-22)) = a*p_11 (principal: 0+1*sqrt-22)
  - Norm 23: split prime gives 2 principal ideals (since 23 = (1)^2 + 22*(1)^2)

The CMR class group action SWAPS principal sector ↔ non-principal sector
(via endomorphism mu_a where a is the non-principal generator).

For ECI: this is the OPERATOR-ALGEBRAIC origin of two M143 quark CM points
linking via Cl(O_K) — they are NOT independent, they are members of a SINGLE
KMS_beta orbit under the Cl(O_K) endomorphism action.
""")

print("="*70)
print("CONCLUSION (M149)")
print("="*70)
print("""
VERDICT: (B) REDUCED with explicit construction.

The CMR Bost-Connes operator algebra (A_{K_Q}, sigma_t) for K_Q = Q(sqrt(-22)),
h_K = 2 EXISTS (CMR Theorem 5.1 — the construction is INDEPENDENT of class number,
contrary to the (erroneous) M144 SUMMARY claim that the construction was
"for K = Q(i), h_K = 1").

The embedding q_{tau_Q}: K_Q^* → GL_2^+(Q) for the non-principal CM point
tau_Q = i*sqrt(11/2) IS:
  q_{tau_Q}(a + b*sqrt(-22)) = [[a, -11*b], [2*b, a]]

This embedding fixes tau_Q as Möbius action (verified mpmath dps=30 to
err < 10^{-30}). It is q_{principal} CONJUGATED by g_Q = diag(1, 2) ∈ GL_2^+(Q).

The Hamiltonian on the CMR Hilbert space ell^2(J ⊂ O_K) is:
  H eps_J = log(n(J)) eps_J
identical formula to Q(i) case, with h_K = 2 manifest in the partition function:
  Z(beta) = zeta_{K_Q}(beta) = zeta(beta) * L(beta, chi_{-88})
which has residue at s=1 = pi/sqrt(22) (vs pi/4 for Q(i)).

The class group Cl(O_K) = Z/2 acts on KMS_beta states by ENDOMORPHISMS modulo
inner (CMR Prop 4.14, Eq 4.4 + 4.28). The non-trivial class corresponds to the
ideal a = (2, sqrt(-22)) and its endomorphism mu_a links principal sector and
non-principal sector. This is OPERATOR-ALGEBRAIC origin of why both CM points
tau_principal = sqrt(-22) and tau_Q = sqrt(-22)/2 enter ECI.
""")
