"""
M179 Test 3 — Maxwell U(1) from Q(i) via Connes-Chamseddine spectral action

Setting (user M179 brief):
  Q(i) class group ↔ rotation group SO(2) ≅ U(1)
  M144 q_i: a+bi ↦ ((a,-b),(b,a)) IS the rotation matrix embedding
  Compute spectral action on the SUGRA Kähler manifold (𝓗, K = -3 log 2 Im τ).
  What gauge group emerges?

VERBATIM FROM CHAMSEDDINE-CONNES 1996 (hep-th/9606001) READ pp 1-15:

Eq (1.23):  D = D_0 + A + J A J^{-1},  A = Σ a_i [D_0, b_i]    inner fluctuations

p.6 verbatim:
   "These fluctuations are trivial: D = D_0 in the usual Riemannian case
    in the same way as the group of inner automorphisms Int(A) = {1} is
    trivial for A = C^∞(M)."

Eq (2.1) Einstein-Yang-Mills test case:
   A = C^∞(M) ⊗ M_N(C),  H = L²(M, S) ⊗ M_N(C),  D = ∂_M ⊗ 1
   p.8 verbatim:
   "Starting with (2.1), one first computes the internal fluctuations of
    the metric and finds that they are parametrized exactly by an SU(N)
    Yang Mills field A. Note that the formula D = D_0 + A + J A J*
    eliminates the U(1) part of A even if one starts with an U(N) gauge
    potential."

§3 Standard Model:
   A_F = C ⊕ H ⊕ M_3(C)  →  U(1) × SU(2) × SU(3) gauge group
   Eq (1.16): A = C^∞(M) ⊗ A_F   (almost commutative geometry)

CRITICAL CONSEQUENCE FOR ECI:

 1. Pure C^∞(H/PSL(2,Z)) gives NO gauge field.  Inner fluctuations
    vanish for commutative A.

 2. To get U(1) Maxwell, we need a NON-TRIVIAL finite spectral triple.
    The standard example is A_F = C ⊕ C (two-point geometry, the
    "two-sheeted spacetime") which gives a U(1) gauge field plus a
    real scalar (Higgs-like).  See Connes 1994 NCG book §VI.

 3. The q_i embedding C^∞(M) ⊗ Z[i] is NOT a finite spectral triple;
    Z[i] is INFINITE-dimensional (lattice in C).  We need a quotient
    or finite reduction.  Z[i]/N for some norm N gives finite C^∞(M)
    ⊗ C^k.

 4. The class group Cl(Q(i)) = trivial (h_K = 1).  So no class-group
    U(1) is forthcoming from arithmetic Cl(K).

 5. The unit group O*_K = {±1, ±i} = Z/4  for K = Q(i).  This gives a
    DISCRETE Z/4 cyclic group, NOT continuous U(1).
"""
import sympy as sp
import mpmath
from sympy import I, Matrix, sqrt, Rational, pi, symbols, exp, log, diff
mpmath.mp.dps = 30

print("="*68)
print("Test 3a — q_i embedding properties")
print("="*68)
print()

# q_i embedding from M144
a, b = symbols('a b', real=True)
M = Matrix([[a, -b], [b, a]])
print(f"q_i: a+bi ↦ {M.tolist()}  (rotation matrix, M144)")
print()

# Properties of q_i image
det_M = M.det()
print(f"det(q_i(a+bi)) = a² + b² = N(a+bi) (norm)")
print(f"trace(q_i(a+bi)) = 2a = 2 Re(a+bi)")
print(f"q_i(1) = identity, q_i(i) = ((0,-1),(1,0)) = J (90° rotation)")
print()
print("q_i restricted to UNIT GROUP O*_K = {±1, ±i}:")
print(f"  q_i(1) = ((1,0),(0,1)) = I")
print(f"  q_i(-1) = ((-1,0),(0,-1)) = -I")
print(f"  q_i(i) = ((0,-1),(1,0)) = J  (i.e. 90° rotation)")
print(f"  q_i(-i) = ((0,1),(-1,0)) = -J")
print()
print("=> q_i(O*_K) = Z/4 cyclic, generated by J.")
print("   This is a DISCRETE finite group, NOT a continuous U(1).")
print()

# Continuous extension: q_i(SO(2)) ⊂ GL_2(R)
print("Continuous extension: q_i extended to a+bi ∈ S¹ ⊂ Q(i)*/R*")
print(f"  q_i(cos θ + i sin θ) = ((cos θ, -sin θ),(sin θ, cos θ))")
print(f"  This IS SO(2) ≅ U(1).")
print()
print("So the GROUP EMBEDDING q_i: U(1) ↪ GL_2(R)  IS continuous.")
print("BUT: this is a CLASSICAL group action on H, NOT a spectral triple gauge field.")
print()

# ─── The crucial Test 3b ───
print("="*68)
print("Test 3b — Connes-Chamseddine spectral action on (H/PSL(2,Z), Kähler 3)")
print("="*68)
print()
print("Spectral triple input:")
print("  A = C^∞(H/PSL(2,Z))  (commutative algebra of smooth functions)")
print("  H = L²(H/PSL(2,Z), S) (spinors)")
print("  D = Dirac operator of Levi-Civita connection of Kähler 3 metric")
print()
print("Inner fluctuations:")
print("  D → D + A + JAJ^{-1},  A = Σ a_i [D, b_i]")
print()
print("Since A is commutative, [D, b] for b ∈ A gives a_i pure derivatives,")
print("and the entire 1-form sector reduces to pure metric (no gauge fields).")
print()
print("VERBATIM (Chamseddine-Connes 1996 p.6):")
print(' "These fluctuations are trivial: D = D_0 in the usual Riemannian case')
print('  in the same way as the group of inner automorphisms Int(A) = {1} is')
print('  trivial for A = C^∞(M)."')
print()
print("=> NO Maxwell U(1) emerges from the SUGRA Kähler manifold ALONE.")
print()

# ─── Test 3c: Finite spectral triple A_F enrichment ───
print("="*68)
print("Test 3c — Almost-commutative enrichment for U(1)")
print("="*68)
print()
print("To produce U(1) Maxwell field, we need an almost-commutative A:")
print("  A = C^∞(M) ⊗ A_F")
print()
print("Candidate finite spectral triples for U(1):")
print("  (i)  A_F = C ⊕ C      (two-point geometry, gives U(1) × U(1) → U(1)_diag)")
print("  (ii) A_F = M_2(C)      (gives SU(2), matches M148: NOT U(1))")
print("  (iii) A_F = H quaternions (gives SU(2), Connes-Chamseddine SM)")
print("  (iv) A_F = Z/4 (= O*_{Q(i)})  DISCRETE, NOT a C-algebra in the right sense")
print()
print("Option (i) C ⊕ C is the only one giving a single U(1).  This")
print("corresponds to the 'two-sheeted spacetime' (M × Z_2 in Connes' early")
print("model).  The two sheets are 'left' and 'right' chiralities, and")
print("inner fluctuations give a U(1) Higgs scalar + a U(1) gauge field at")
print("the Wick-rotated level.")
print()
print("BUT: there is no natural ECI-internal reason to choose Z_2 = {τ_a, τ_b}")
print("Kähler-norm orbit (M174 §3) as a SPECTRAL SHEET pair.  The Z_2 in M174")
print("is τ_a = i√22 and τ_b = i√(11/2), Kähler-distance Δφ = (√3/2) log 2.")
print("These two POINTS in H/PSL(2,Z) both have the SAME spectral data")
print("(same Kähler curvature K = -2/3); they are not 'two sheets' in the")
print("Connes-Chamseddine sense.  They are two DIFFERENT vacua of V_F with")
print("the same metric.")
print()

# ─── Test 3d: q_i action on H_F ? ───
print("="*68)
print("Test 3d — q_i embedding as a candidate finite spectral triple?")
print("="*68)
print()
print("Could q_i: Q(i)* → GL_2(Q) define a finite spectral triple?")
print()
print("Q(i) is INFINITE-dimensional as a Q-vector space (rank 2 over Q)")
print("BUT as a complex algebra Q(i) ⊗_Q C ≅ C ⊕ C (it splits).")
print()
print("Spectral triple from Q(i):")
print("  A_F = Q(i) ⊗_Q C ≅ C ⊕ C")
print("  H_F = C² (with q_i action)")
print("  D_F = Y_0 = some 2x2 mass matrix")
print()
print("This IS the two-point spectral triple A_F = C ⊕ C !")
print()
print("Inner fluctuations of A = C^∞(H/PSL(2,Z)) ⊗ (C ⊕ C):")
print("  Gauge field: U(1)_+ × U(1)_-  (one for each C copy)")
print("  After J A J* projection: U(1) survives  (Connes-Chamseddine 1996 §2)")
print("  Higgs: scalar field connecting the two C copies")
print()
print("** CRITICAL CORRECTION (verified Connes-Marcolli book + Connes 2019) **:")
print()
print("In the two-point spectral triple A_F = C ⊕ C with finite Hilbert")
print("space H_F = C^2 and operator D_F = ((0, μ), (μ̄, 0)) (off-diagonal):")
print()
print("  Inner fluctuations A = Σ a_i [D_F, b_i] for a, b ∈ C ⊕ C")
print("  give a SCALAR Higgs field, NOT a U(1) gauge field.")
print()
print("Reason: [D_F, b] for b = (b_+, b_-) computes (b_+ - b_-) in the")
print("off-diagonal slots, which is a DISCRETE DIFFERENCE = a scalar")
print("along the discrete Z_2 direction.  Local rotations on the two-sheet")
print("don't change this scalar.  This is exactly the geometric origin of")
print("the Brout-Englert-Higgs field (Connes 'two-sheeted spacetime').")
print()
print("=> A_F = C ⊕ C gives HIGGS, NOT MAXWELL U(1).")
print()
print("To get a U(1) gauge field, the algebra must be either:")
print("  (a) Non-commutative finite (e.g. M_N(C) for N >= 2 → SU(N))")
print("  (b) C^∞(M) for M a continuum manifold (gauge field = 1-form)")
print()
print("In case (b), inner fluctuations Σ a_i [D, b_i] for commutative")
print("C^∞(M) are TRIVIAL by Chamseddine-Connes 1996 p.6 verbatim.")
print()
print("=> So the Q(i) ⊗_Q C ≅ C ⊕ C path produces a HIGGS-LIKE SCALAR")
print("   from the discrete Z_2 splitting, NOT a Maxwell U(1).")
print()
print("This is consistent with M174 §3 Z_2 class-group orbit (τ_a, τ_b):")
print("  Δφ = (√3/2) log 2 = scalar field difference between two vacua")
print("  This Z_2 is precisely the two-sheet structure giving a HIGGS scalar.")
print("  M174 already classified this as 'topological vacuum selection'.")
print()

# ─── Final: actual gauge group emerging ───
print("="*68)
print("Test 3e — Synthesis: which gauge group ACTUALLY emerges?")
print("="*68)
print()
print("Algebra A = C^∞(H/PSL(2,Z)) ⊗ Q(i) ⊗_Q C")
print("        = C^∞(H/PSL(2,Z)) ⊗ (C ⊕ C)")
print()
print("Inner fluctuations of D = D_M ⊗ 1 + γ_5 ⊗ D_F:")
print("  - Continuum sector (C^∞(M)):  TRIVIAL (Chamseddine-Connes 1996 p.6)")
print("  - Discrete sector (C ⊕ C):    SCALAR HIGGS FIELD, NO GAUGE FIELD")
print()
print("=> Net emergent bosonic content: ONE real scalar Higgs-like field")
print("   between the τ_a and τ_b vacua.")
print("   NO Maxwell U(1) emerges.")
print()
print("To get any GAUGE FIELD, we'd need either:")
print("  - Non-commutative A_F (e.g. M_2(C) → SU(2), M_3(C) → SU(3))")
print("  - Larger algebra Q(i) ⊗_Q M_N(C) etc., which has no arithmetic")
print("    motivation from Q(i) class field theory or M144 q_i embedding.")
print()
print("VERDICT for Test 3 (Maxwell U(1) from Q(i) via spectral action):")
print()
print("(C) NEGATIVE — pure Q(i) ⊗_Q C = C ⊕ C cannot produce Maxwell U(1).")
print("    It produces a Higgs-like real scalar between the two Z_2-related")
print("    vacua (τ_a, τ_b) in M174's class-group orbit.  This is internally")
print("    consistent: the M174 Δφ = (√3/2) log 2 IS a scalar field difference.")
print()
print("(D) PARTIAL salvage — the Higgs-scalar interpretation of the M174 Z_2")
print("    orbit is structurally meaningful: the Connes 'two-sheet ↦ Higgs'")
print("    mechanism gives a CONCEPTUAL identification of the τ_a-τ_b mode")
print("    as a Higgs-like scalar.  But no Maxwell U(1) and no quantitative")
print("    bypass of M174/M175 obstructions.")
print()
print("Probability post-Test-3: (C) ≥ 60%, (D) ~ 35%, (B) ~ 5%, (A) < 1%.")
