"""
H3 — Chern/Pontryagin characteristic class degree interpretation of
the exponents (a, b, c, d).

Brief proposal:
  a ∈ {0, 1/2, 1, 2}
  b ∈ {-1/2, 0, 1}
  c ∈ {0, 1/2}
  d ∈ {-1/2, 0, 1/2}

Mapping:
  a = degree of a kappa-class on the gauge orbit space A/G
  b = degree of (1-kappa) class
  c = degree of (1+kappa) class
  d = degree of pi class

Characteristic classes on BSU(3) (classifying space of SU(3)):
  H*(BSU(3); Q) = Q[c_2, c_3]
  with degree(c_2) = 4, degree(c_3) = 6.

Characteristic classes on BG for compact simple G:
  H*(BG; Q) = Q[generators of degree 2k for invariants of g]
  For SU(N): generators in degrees 4, 6, ..., 2N.
  For SU(3): degrees 4 (c_2) and 6 (c_3).

Pontryagin classes for SO(N):
  p_i ∈ H^{4i}(BSO(N); Q), generated for i = 1, ..., [N/2]
  For SO(3): p_1 ∈ H^4.
  Half-class p_1/2 lives in H^4(BSU(2); Z) since BSU(2) -> BSO(3) is 2-to-1 cover.

Atiyah-Bott 1983 cohomology of moduli space of stable bundles M_g(SL_n,d)
on a Riemann surface of genus g, rank n, degree d:
  H*(M; Q) is generated by KÜNNETH classes a_r, b_r^i (i=1..2g), f_r
  for r = 2, ..., n (degrees 2r-2, 2r-1, 2r), pulled back from the
  Atiyah-Bott classes a_r = c_r(E) where E is the universal bundle.

For SU(3): classes have degrees
  a_2 (deg 2), b_2^i (deg 3, i=1..2g), f_2 (deg 4)
  a_3 (deg 4), b_3^i (deg 5), f_3 (deg 6)

If kappa enters via the integral
  ∫_M [class of degree 2k] = const · kappa^k
then exponent of kappa should match degree/2.

But the brief's pattern table shows:
  - kappa^1 (Koide K = 4*kappa)
  - kappa^0.5 (sigma_8 = sqrt(2/3) = 2*sqrt(kappa))
  - kappa^2 ? (not yet observed; would be (1-kappa^2) = 1 - kappa^2)
  - V_ud = 1 - kappa^2 has FORMAL exponent (0, 1, 1, 0, 1) (factored)
    OR (a=2, b=0, c=0, d=0) if we expand: 1 - kappa^2 has "kappa^2" term
    inside it as a polynomial, but the leading constant is 1.

The (a, b, c, d, rat) factorization of the brief is MULTIPLICATIVE:
  O = kappa^a * (1-kappa)^b * (1+kappa)^c * pi^d * rat
This is well-defined since kappa, (1-kappa), (1+kappa), pi are all
linearly independent over Q.

So a = "homogeneous degree in kappa", which can be interpreted as
characteristic class degree of an INVARIANT POLYNOMIAL in kappa-fluctuations.
"""

import numpy as np
import math

# Let me check the consistency of exponent a with class degree
# for the patterns where the empirical exponent is clear:

patterns_with_a = [
    ("K_charged_leptons = 4*kappa",       1, "Casimir of SU(3) = (N^2-1)/N = 8/3? No, C_2(adj)=N=3 for SU(3)"),
    ("BH_prefactor = 1/4 = (3/2)*kappa",  1, "1/4 = (3/2)*(1/6)"),
    ("sigma_8 = 2*sqrt(kappa)",          1/2, "sqrt = half-Pontryagin?"),
    ("V_ud = (1-kappa)(1+kappa) = 1-kappa^2", 0, "Outside kappa^a but 1-kappa^2 hides degree-2"),
    ("alpha_LSI = 1-kappa = (1-kappa)^1", 0, "exponent of kappa is 0; b=1"),
    ("m_p/Lambda = pi/(1-kappa)",         0, "b=-1, d=1; a=0"),
    ("m_0-+/m_0++ = 3/2",                  0, "no kappa: a=0, all zero"),
]

print("Class degree interpretation:")
print(f"{'pattern':<45}{'a':>3}  {'comment'}")
print("-"*100)
for label, a, comment in patterns_with_a:
    print(f"{label:<45}{a:>3}  {comment}")

print()
print("="*60)
print("Cosmology of exponent a values in 17 patterns")
print("="*60)
print("a=0: 'no kappa-class' i.e. the leading term in kappa-expansion")
print("a=1/2: half-degree Pontryagin-like class")
print("a=1: linear-in-kappa class (Atiyah-Bott a_2 of degree 2)")
print("a=2: quadratic-in-kappa class (could be c_2^2 or similar)")
print()
print("In Atiyah-Bott (1983) the universal bundle has classes:")
print("  a_2 ∈ H^2, a_3 ∈ H^4 (for SU(3))")
print("  f_2 ∈ H^4, f_3 ∈ H^6 (for SU(3))")
print("  b_r^i ∈ H^{2r-1} (odd degree, vanishes for our 17 patterns")
print("                    since all observables are 'even/scalar')")
print()
print("Map (Atiyah-Bott degree) -> (kappa-power a):")
print("   H^0 -> a = 0   (constants)")
print("   H^2 -> a = 1   (a_2 = c_2 in this rank=3 framework)")
print("   H^4 -> a = 2   (a_3, f_2)")
print("   H^6 -> a = 3   (f_3)")
print()
print("Half-degrees from spinors:")
print("   H^1 (spinor first descendant) -> a = 1/2")
print("   H^3 -> a = 3/2")
print()
print("This matches the brief's a ∈ {0, 1/2, 1, 2}!")
print("Specifically: a ∈ {0, 1/2, 1, 2} = degrees /2 ∈ {0, 1/4, 1/2, 1}")
print("which are degrees in H^{0,1,2,4} reading 'a = (deg)/2'")
print()

print("="*60)
print("Check: does the kappa-exponent a correspond to Pontryagin/Chern degree?")
print("="*60)
print()

# Pontryagin class p_1(M^4) integrated over M^4 gives instanton number
# p_1 ~ Tr(F ^ F) / (8 pi^2)
# So p_1^k contributes (kappa)^k to spectral asymptotics if kappa parameterizes
# the saddle-point expansion around instanton sectors.

# The Atiyah-Bott formula for the volume of M_g(SU_n, d):
# Vol(M_g(SU_n, d)) = (1/n) * (2*pi)^{...} * zeta(2) * zeta(4) * ... * zeta(2n-2)
#                  * Riemann-Hurwitz factor
# Witten 1991 formulas show that volumes of moduli spaces are polynomial in (1/k)
# where k is the level, which gets identified with kappa here.

# For SU(2), gamma = genus 2: Vol(M_2(SU_2)) = pi^2/3 + ...
# For SU(3): Vol(M_2(SU_3)) involves pi^? and zeta values.

# CRITICAL: the kappa-power 'a' should equal the "instanton-class power"
# in the kappa-expansion of the partition function.

# In our framework, kappa appears multiplicatively as:
#   c_LSI = (1-kappa) * c_Pinsker
# So at first order in instanton corrections, kappa^1.
# At second order, kappa^2.
# This matches the brief's a ∈ {0, 1, 2}.
# The half-integer a = 1/2 corresponds to spinor sectors: half-instantons,
# i.e. solutions of the self-dual Yang-Mills equations on a manifold with
# torsion in pi_1(M).

# Now exponent b: linear in (1-kappa).
# (1-kappa) is the (1, 1)-correction. Each factor of (1-kappa) = c_Pinsker / c_LSI
# represents one "renormalization unit".
# b can be {-1/2, 0, 1}:
#   b=1: one ren-unit (e.g. alpha_LSI = 1-kappa)
#   b=-1: inverse renormalization (e.g. m_p/Lambda = pi/(1-kappa))
#   b=-1/2 or +1/2: half-renormalization (spinor/half-flux)

# Exponent c ∈ {0, 1/2}: (1+kappa) appears in:
#   V_ud = (1-kappa)(1+kappa): c=1, but here c was supposed to be {0, 1/2}!
# WAIT - brief says c ∈ {0, 1/2}. Let me re-read.

# Brief: c ∈ {0, 1/2}. But V_ud has c=1 not c=1/2.
# Either V_ud uses c=1 (outside brief's range) OR V_ud is not in template.
# Let me re-examine.

print("CHECKING brief's exponent ranges vs. 17 patterns:")
print("Brief: a ∈ {0, 1/2, 1, 2}, b ∈ {-1/2, 0, 1}, c ∈ {0, 1/2}, d ∈ {-1/2, 0, 1/2}")
print()
print("Census of observed exponents:")
print("  a values observed: {0, 1/2, 1}     (subset of {0, 1/2, 1, 2})")
print("  b values observed: {-1, 0, 1}      (NOT subset; -1 not in brief but observed in m_p/Lambda)")
print("  c values observed: {0, 1}          (NOT subset; 1 not in brief but observed in V_ud)")
print("  d values observed: {0, 1}          (NOT subset; 1 not in brief but observed in m_p/Lambda)")
print()
print("DISCREPANCY: The brief's grid (4*3*2*3 = 72) does NOT contain all observed exponents.")
print("In particular:")
print("  m_p/Lambda = pi^1 / (1-kappa)^1 uses b=-1, d=1 (not in brief grid {-1/2, 0, 1})")
print("  V_ud = (1-kappa)(1+kappa) uses c=1 (not in brief grid {0, 1/2})")
print()
print("Either the brief's grid is wrong, or my pattern parsing is wrong, or...")
print()
print("RESOLUTION: the brief grid {a, b, c, d} may be a TARGET SUBSET.")
print("The 17 patterns might OVERSHOOT this range, suggesting H3 is too narrow.")
