# Build the variational-basis glueball_correlator_v3 binary.
#
# This links against an installed Chroma + QDP++ + QMP stack.
# If chroma-config is available, use it; otherwise use manual paths.
#
# Usage:
#   make -f Makefile.glueball_v3
#
# Requires: mpicxx (MPI C++14 compiler), Chroma libraries, libxml2

CHROMA  ?= $(HOME)/install/chroma
QDPXX   ?= $(HOME)/install/qdpxx
QMP     ?= $(HOME)/install/qmp

CXX     := mpicxx
CHROMA_CONF := $(CHROMA)/bin/chroma-config
HAS_CHROMA_CONFIG := $(shell test -x $(CHROMA_CONF) && echo yes)

ifeq ($(HAS_CHROMA_CONFIG),yes)
  CXXFLAGS := -std=c++14 -O2 -g $(shell $(CHROMA_CONF) --cxxflags)
  LIBS     := $(shell $(CHROMA_CONF) --ldflags) $(shell $(CHROMA_CONF) --libs)
else
  CXXFLAGS := -std=c++14 -O2 -g \
              -I$(CHROMA)/include -I$(QDPXX)/include -I$(QMP)/include \
              -I/usr/include/libxml2
  LIBS     := -L$(CHROMA)/lib -lchroma \
              -L$(QDPXX)/lib  -lqdp \
              -L$(QMP)/lib    -lqmp \
              -lxml2
endif

all: glueball_correlator_v3

glueball_correlator_v3: glueball_correlator_v3.cc
	$(CXX) $(CXXFLAGS) -o $@ $< $(LIBS)

clean:
	rm -f glueball_correlator_v3

test: glueball_correlator_v3
	@echo "=== Sanity: binary exists ==="
	@file glueball_correlator_v3
	@echo "=== Compilation OK ==="
